(DEFPACKAGE #:SIMPLE-DIRECTMEDIA-LAYER (:USE #:CL #:CFFI) (:NICKNAMES #:SDL)
            (:EXPORT #:+LIL-ENDIAN+ #:+BIG-ENDIAN+ #:+BYTEORDER+ #:+BYTEORDER+
		     #:VIDEO-INFO #:BOOL #:UINT64 #:DUMMY-ENUM #:GETENV #:PUTENV
		     #:GET-TICKS #:DELAY #:HWND #:HGLRC #:HDC #:GET-ERROR #:CLEAR-ERROR
		     #:ERRORCODE #:SDL-ERROR #:RW-OPS #:RW-OPS-HIDDEN
		     #:RW-OPS-HIDDEN-UNKNOWN #:RW-OPS-HIDDEN-MEM #:RW-FROM-FILE
		     #:RW-FROM-MEM #:RW-FROM-CONST-MEM #:ALLOC-RW #:FREE-RW
		     #:+RW-SEEK-SET+ #:+RW-SEEK-CUR+ #:+RW-SEEK-END+ #:READ-LE16
		     #:READ-BE16 #:READ-LE32 #:READ-BE32 #:READ-LE64 #:READ-BE64
		     #:WRITE-LE16 #:WRITE-BE16 #:WRITE-LE32 #:WRITE-BE32 #:WRITE-LE64
		     #:WRITE-BE64 #:AUDIO-SPEC #:+AUDIO-U8+ #:+AUDIO-S8+
		     #:+AUDIO-U16-LSB+ #:+AUDIO-S16-LSB+ #:+AUDIO-U16-MSB+
		     #:+AUDIO-S16-MSB+ #:+AUDIO-U16+ #:+AUDIO-S16+ #:AUDIO-CVT
		     #:AUDIO-INIT #:AUDIO-QUIT #:AUDIO-DRIVER-NAME #:OPEN-AUDIO
		     #:AUDIOSTATUS #:GET-AUDIO-STATUS #:PAUSE-AUDIO #:LOAD-WAV-RW
		     #:FREE-WAV #:BUILD-AUDIO-CVT #:CONVERT-AUDIO #:+MIX-MAXVOLUME+
		     #:MIX-AUDIO #:LOCK-AUDIO #:UNLOCK-AUDIO #:CLOSE-AUDIO
		     #:+MAX-TRACKS+ #:+AUDIO-TRACK+ #:+DATA-TRACK+ #:CD-STATUS
		     #:CD-TRACK #:CD #:CD-NUM-DRIVES #:CD-NAME #:CD-OPEN #:CD-STATUS
		     #:CD-PLAY-TRACKS #:CD-PLAY #:CD-PAUSE #:CD-RESUME #:CD-STOP
		     #:CD-EJECT #:CD-CLOSE #:NUM-JOYSTICKS #:JOYSTICK-NAME
		     #:JOYSTICK-OPEN #:JOYSTICK-OPENED #:JOYSTICK-INDEX
		     #:JOYSTICK-NUM-AXES #:JOYSTICK-NUM-BALLS #:JOYSTICK-NUM-HATS
		     #:JOYSTICK-NUM-BUTTONS #:JOYSTICK-UPDATE #:JOYSTICK-EVENT-STATE
		     #:JOYSTICK-GET-AXIS #:+HAT-CENTERED+ #:+HAT-UP+ #:+HAT-RIGHT+
		     #:+HAT-DOWN+ #:+HAT-LEFT+ #:JOYSTICK-GET-HAT #:JOYSTICK-GET-BALL
		     #:JOYSTICK-GET-BUTTON #:JOYSTICK-CLOSE #:+APPMOUSEFOCUS+
		     #:+APPINPUTFOCUS+ #:+APPACTIVE+ #:GET-APP-STATE #:SDL-KEY
		     #:SDL-MOD #:KEYSYM #:+ALL-HOTKEYS+ #:ENABLE-UNICODE
		     #:+DEFAULT-REPEAT-DELAY+ #:+DEFAULT-REPEAT-INTERVAL+
		     #:ENABLE-KEY-REPEAT #:GET-KEY-REPEAT #:GET-KEY-STATE
		     #:GET-MOD-STATE #:SET-MOD-STATE #:GET-KEY-NAME #:CURSOR
		     #:GET-MOUSE-STATE #:GET-RELATIVE-MOUSE-STATE #:WARP-MOUSE
		     #:CREATE-CURSOR #:SET-CURSOR #:GET-CURSOR #:FREE-CURSOR
		     #:SHOW-CURSOR #:+BUTTON-LEFT+ #:+BUTTON-MIDDLE+ #:+BUTTON-RIGHT+
		     #:+BUTTON-WHEELUP+ #:+BUTTON-WHEELDOWN+ #:+RELEASED+ #:+PRESSED+
		     #:EVENT-TYPE #:+ALLEVENTS+ #:ACTIVE-EVENT #:KEYBOARD-EVENT
		     #:MOUSE-MOTION-EVENT #:MOUSE-BUTTON-EVENT #:JOY-AXIS-EVENT
		     #:JOY-BALL-EVENT #:JOY-HAT-EVENT #:JOY-BUTTON-EVENT #:RESIZE-EVENT
		     #:EXPOSE-EVENT #:QUIT-EVENT #:USER-EVENT #:SYS-WM-EVENT #:EVENT
		     #:PUMP-EVENTS #:EVENTACTION #:PEEP-EVENTS #:POLL-EVENT
		     #:WAIT-EVENT #:PUSH-EVENT #:SET-EVENT-FILTER #:GET-EVENT-FILTER
		     #:+QUERY+ #:+IGNORE+ #:+DISABLE+ #:+ENABLE+ #:EVENT-STATE
		     #:+ALPHA-OPAQUE+ #:+ALPHA-TRANSPARENT+ #:RECT #:COLOR #:PALETTE
		     #:PIXEL-FORMAT #:SURFACE #:+SWSURFACE+ #:+HWSURFACE+ #:+ASYNCBLIT+
		     #:+ANYFORMAT+ #:+HWPALETTE+ #:+DOUBLEBUF+ #:+FULLSCREEN+
		     #:+OPENGL+ #:+OPENGLBLIT+ #:+RESIZABLE+ #:+NOFRAME+ #:+HWACCEL+
		     #:+SRCCOLORKEY+ #:+RLEACCELOK+ #:+RLEACCEL+ #:+SRCALPHA+
		     #:+PREALLOC+ #:+YV12-OVERLAY+ #:+IYUV-OVERLAY+ #:+YUY2-OVERLAY+
		     #:+UYVY-OVERLAY+ #:+YVYU-OVERLAY+ #:OVERLAY #:GL-ATTR #:+LOGPAL+
		     #:+PHYSPAL+ #:VIDEO-INIT #:VIDEO-QUIT #:VIDEO-DRIVER-NAME
		     #:GET-VIDEO-SURFACE #:GET-VIDEO-INFO #:VIDEO-MODE-OK #:LIST-MODES
		     #:SET-VIDEO-MODE #:UPDATE-RECTS #:UPDATE-RECT #:FLIP #:SET-GAMMA
		     #:SET-GAMMA-RAMP #:GET-GAMMA-RAMP #:SET-COLORS #:SET-PALETTE
		     #:MAP-RGB #:MAP-RGBA #:GET-RGB #:GET-RGBA #:CREATE-RGB-SURFACE
		     #:CREATE-RGB-SURFACE-FROM #:FREE-SURFACE #:LOCK-SURFACE
		     #:UNLOCK-SURFACE #:LOAD-BMP-RW #:SAVE-BMP-RW #:SET-COLOR-KEY
		     #:SET-ALPHA #:SET-CLIP-RECT #:GET-CLIP-RECT #:CONVERT-SURFACE
		     #:UPPER-BLIT #:LOWER-BLIT #:FILL-RECT #:DISPLAY-FORMAT
		     #:DISPLAY-FORMAT-ALPHA #:CREATE-YUV-OVERLAY #:LOCK-YUV-OVERLAY
		     #:UNLOCK-YUV-OVERLAY #:DISPLAY-YUV-OVERLAY #:FREE-YUV-OVERLAY
		     #:GL-LOAD-LIBRARY #:GL-GET-PROC-ADDRESS #:GL-SET-ATTRIBUTE
		     #:GL-GET-ATTRIBUTE #:GL-SWAP-BUFFERS #:GL-UPDATE-RECTS #:GL-LOCK
		     #:GL-UNLOCK #:WM-SET-CAPTION #:WM-GET-CAPTION #:WM-SET-ICON
		     #:WM-ICONIFY-WINDOW #:WM-TOGGLE-FULL-SCREEN #:GRAB-MODE
		     #:WM-GRAB-INPUT #:SOFT-STRETCH #:+MAJOR-VERSION+ #:+MINOR-VERSION+
		     #:+PATCHLEVEL+ #:VERSION #:LINKED-VERSION #:+INIT-TIMER+
		     #:+INIT-AUDIO+ #:+INIT-VIDEO+ #:+INIT-CD-ROM+ #:+INIT-JOYSTICK+
		     #:+INIT-NOPARACHUTE+ #:+INIT-EVENTTHREAD+ #:+INIT-EVERYTHING+
		     #:INIT #:INIT-SUB-SYSTEM #:QUIT-SUB-SYSTEM #:WAS-INIT #:QUIT
		     #:PATCH #:MINOR #:MAJOR #:UNUSEDBITS #:HW_OVERLAY #:HWDATA
		     #:HWFUNCS #:PIXELS #:PITCHES #:PLANES #:H #:W #:FORMAT #:REFCOUNT
		     #:FORMAT_VERSION #:MAP #:LOCKED #:UNUSED1 #:CLIP_RECT #:HWDATA
		     #:OFFSET #:PIXELS #:PITCH #:H #:W #:FORMAT #:FLAGS #:ALPHA
		     #:COLORKEY #:AMASK #:BMASK #:GMASK #:RMASK #:ASHIFT #:BSHIFT
		     #:GSHIFT #:RSHIFT #:ALOSS #:BLOSS #:GLOSS #:RLOSS #:BYTESPERPIXEL
		     #:BITSPERPIXEL #:PALETTE #:COLORS #:NCOLORS #:UNUSED #:B #:G #:R
		     #:H #:W #:Y #:X #:MSG #:TYPE #:DATA2 #:DATA1 #:CODE #:TYPE #:TYPE
		     #:TYPE #:H #:W #:TYPE #:STATE #:BUTTON #:WHICH #:TYPE #:VALUE
		     #:HAT #:WHICH #:TYPE #:YREL #:XREL #:BALL #:WHICH #:TYPE #:VALUE
		     #:AXIS #:WHICH #:TYPE #:Y #:X #:STATE #:BUTTON #:WHICH #:TYPE
		     #:YREL #:XREL #:Y #:X #:STATE #:WHICH #:TYPE #:KEYSYM #:STATE
		     #:WHICH #:TYPE #:STATE #:GAIN #:TYPE #:WM_CURSOR #:SAVE #:MASK
		     #:DATA #:HOT_Y #:HOT_X #:AREA #:UNICODE #:MOD #:SYM #:SCANCODE
		     #:TRACK #:CUR_FRAME #:CUR_TRACK #:NUMTRACKS #:STATUS #:ID #:OFFSET
		     #:LENGTH #:UNUSED #:TYPE #:ID #:FILTER_INDEX #:FILTERS #:LEN_RATIO
		     #:LEN_MULT #:LEN_CVT #:LEN #:BUF #:RATE_INCR #:DST_FORMAT
		     #:SRC_FORMAT #:NEEDED #:USERDATA #:CALLBACK #:SIZE #:PADDING
		     #:SAMPLES #:SILENCE #:CHANNELS #:FORMAT #:FREQ #:STOP #:HERE
		     #:BASE #:DATA1 #:HIDDEN #:TYPE #:CLOSE #:WRITE #:READ #:SEEK
		     #:UNUSED #:UNUSED #:UNUSED #:LO #:HI #:CURRENT_H #:CURRENT_W
		     #:VFMT #:VIDEO_MEM #:FLAGS))
(IN-PACKAGE #:SIMPLE-DIRECTMEDIA-LAYER)
(CFFI:LOAD-FOREIGN-LIBRARY
 '(:OR (:FRAMEWORK "SDL") "SDL.dll" (:DEFAULT "libSDL-1.2")
   (:DEFAULT "SDL-1.2") (:DEFAULT "libSDL") (:DEFAULT "SDL")))
(DEFMACRO DEFENUM (&BODY ENUMS)
  `(PROGN
     ,@(LOOP FOR VALUE IN ENUMS FOR INDEX = 0 THEN (1+ INDEX) WHEN (LISTP VALUE)
	  DO (SETF INDEX (SECOND VALUE) VALUE (FIRST VALUE)) COLLECT
	  `(DEFCONSTANT ,VALUE ,INDEX))))
(DEFUN 1<< (X) (ASH 1 X))
(DEFCONSTANT +LIL-ENDIAN+ 1234)
(DEFCONSTANT +BIG-ENDIAN+ 4321)
(DEFCONSTANT +BYTEORDER+ +LIL-ENDIAN+)
(DEFBITFIELD HARDWARE-FLAGS (:HW_AVAILABLE 0) (:WM_AVAILABLE 1) (:BLIT_HW 512)
	     (:BLIT_HW_CC 1024) (:BLIT_HW_A 2048) (:BLIT_SW 4096) (:BLIT_SW_CC 8192)
	     (:BLIT_SW_A 16384) (:BLIT_FILL 32768))
(CFFI:DEFCSTRUCT VIDEO-INFO (FLAGS HARDWARE-FLAGS) (VIDEO_MEM :UNSIGNED-INT)
                 (VFMT :POINTER) (CURRENT_W :INT) (CURRENT_H :INT))
(CFFI:DEFCENUM BOOL (:FALSE 0) (:TRUE 1))
(CFFI:DEFCSTRUCT UINT64 (HI :UNSIGNED-INT) (LO :UNSIGNED-INT))
(CFFI:DEFCENUM DUMMY-ENUM :DUMMY-ENUM-VALUE)
(CFFI:DEFCFUN ("SDL_getenv" GETENV) :POINTER (NAME :STRING))
(CFFI:DEFCFUN ("SDL_putenv" PUTENV) :INT (VARIABLE :STRING))
(CFFI:DEFCFUN ("SDL_GetTicks" GET-TICKS) :UNSIGNED-INT)
(CFFI:DEFCFUN ("SDL_Delay" DELAY) :VOID (MS :UNSIGNED-INT))
(DEFUN BUTTON (X) (ASH 1 (1- X)))
(DEFMACRO DEFANONENUM (&BODY ENUMS)
  "Converts anonymous enums to defconstants."
  `(PROGN
     ,@(LOOP FOR VALUE IN ENUMS FOR INDEX = 0 THEN (1+ INDEX) WHEN (LISTP VALUE)
	  DO (SETF INDEX (SECOND VALUE) VALUE (FIRST VALUE)) COLLECT
	  `(DEFCONSTANT ,VALUE ,INDEX))))
(EVAL-WHEN (:COMPILE-TOPLEVEL :LOAD-TOPLEVEL)
  (UNLESS (FBOUNDP 'SWIG-LISPIFY)
    (DEFUN SWIG-LISPIFY (NAME FLAG &OPTIONAL (PACKAGE *PACKAGE*))
      (LABELS ((HELPER (LST LAST REST &AUX (C (CAR LST)))
                 (COND ((NULL LST) REST)
                       ((UPPER-CASE-P C)
                        (HELPER (CDR LST) 'UPPER
				(CASE LAST
				  ((LOWER DIGIT) (LIST* C #\- REST))
				  (T (CONS C REST)))))
                       ((LOWER-CASE-P C)
                        (HELPER (CDR LST) 'LOWER (CONS (CHAR-UPCASE C) REST)))
                       ((DIGIT-CHAR-P C)
                        (HELPER (CDR LST) 'DIGIT
				(CASE LAST
				  ((UPPER LOWER) (LIST* C #\- REST))
				  (T (CONS C REST)))))
                       ((CHAR-EQUAL C #\_)
                        (HELPER (CDR LST) '_ (CONS #\- REST)))
                       (T (ERROR "Invalid character: ~A" C)))))
        (LET ((FIX
               (CASE FLAG ((CONSTANT ENUMVALUE) "+") (VARIABLE "*") (T ""))))
          (INTERN
           (CONCATENATE 'STRING FIX
                        (NREVERSE (HELPER (CONCATENATE 'LIST NAME) NIL NIL))
                        FIX)
           PACKAGE))))))
(CFFI:DEFCSTRUCT HWND (UNUSED :INT))
(CFFI:DEFCSTRUCT HGLRC (UNUSED :INT))
(CFFI:DEFCSTRUCT HDC (UNUSED :INT))
(CFFI:DEFCFUN ("SDL_GetError" GET-ERROR) :STRING)
(CFFI:DEFCFUN ("SDL_ClearError" CLEAR-ERROR) :VOID)
(CFFI:DEFCENUM ERRORCODE :ENOMEM :EFREAD :EFWRITE :EFSEEK :UNSUPPORTED
               :LASTERROR)
(CFFI:DEFCFUN ("SDL_Error" SDL-ERROR) :VOID (CODE ERRORCODE))
(CFFI:DEFCSTRUCT RW-OPS (SEEK :POINTER) (READ :POINTER) (WRITE :POINTER)
                 (CLOSE :POINTER) (TYPE :UNSIGNED-INT) (HIDDEN :POINTER))
(CFFI:DEFCUNION RW-OPS-HIDDEN (UNKNOWN :POINTER) (MEM :POINTER))
(CFFI:DEFCSTRUCT RW-OPS-HIDDEN-UNKNOWN (DATA1 :POINTER))
(CFFI:DEFCSTRUCT RW-OPS-HIDDEN-MEM (BASE :POINTER) (HERE :POINTER)
                 (STOP :POINTER))
(CFFI:DEFCFUN ("SDL_RWFromFile" RW-FROM-FILE) :POINTER (FILE :STRING)
              (MODE :STRING))
(CFFI:DEFCFUN ("SDL_RWFromMem" RW-FROM-MEM) :POINTER (MEM :POINTER) (SIZE :INT))
(CFFI:DEFCFUN ("SDL_RWFromConstMem" RW-FROM-CONST-MEM) :POINTER (MEM :POINTER)
              (SIZE :INT))
(CFFI:DEFCFUN ("SDL_AllocRW" ALLOC-RW) :POINTER)
(CFFI:DEFCFUN ("SDL_FreeRW" FREE-RW) :VOID (AREA :POINTER))
(DEFCONSTANT +RW-SEEK-SET+ 0)
(DEFCONSTANT +RW-SEEK-CUR+ 1)
(DEFCONSTANT +RW-SEEK-END+ 2)
(CFFI:DEFCFUN ("SDL_ReadLE16" READ-LE16) :UNSIGNED-SHORT (SRC :POINTER))
(CFFI:DEFCFUN ("SDL_ReadBE16" READ-BE16) :UNSIGNED-SHORT (SRC :POINTER))
(CFFI:DEFCFUN ("SDL_ReadLE32" READ-LE32) :UNSIGNED-INT (SRC :POINTER))
(CFFI:DEFCFUN ("SDL_ReadBE32" READ-BE32) :UNSIGNED-INT (SRC :POINTER))
(CFFI:DEFCFUN ("SDL_ReadLE64" READ-LE64) :POINTER (SRC :POINTER))
(CFFI:DEFCFUN ("SDL_ReadBE64" READ-BE64) :POINTER (SRC :POINTER))
(CFFI:DEFCFUN ("SDL_WriteLE16" WRITE-LE16) :INT (DST :POINTER)
              (VALUE :UNSIGNED-SHORT))
(CFFI:DEFCFUN ("SDL_WriteBE16" WRITE-BE16) :INT (DST :POINTER)
              (VALUE :UNSIGNED-SHORT))
(CFFI:DEFCFUN ("SDL_WriteLE32" WRITE-LE32) :INT (DST :POINTER)
              (VALUE :UNSIGNED-INT))
(CFFI:DEFCFUN ("SDL_WriteBE32" WRITE-BE32) :INT (DST :POINTER)
              (VALUE :UNSIGNED-INT))
(CFFI:DEFCFUN ("SDL_WriteLE64" WRITE-LE64) :INT (DST :POINTER) (VALUE :POINTER))
(CFFI:DEFCFUN ("SDL_WriteBE64" WRITE-BE64) :INT (DST :POINTER) (VALUE :POINTER))
(CFFI:DEFCSTRUCT AUDIO-SPEC (FREQ :INT) (FORMAT :UNSIGNED-SHORT)
                 (CHANNELS :UNSIGNED-CHAR) (SILENCE :UNSIGNED-CHAR)
                 (SAMPLES :UNSIGNED-SHORT) (PADDING :UNSIGNED-SHORT)
                 (SIZE :UNSIGNED-INT) (CALLBACK :POINTER) (USERDATA :POINTER))
(DEFCONSTANT +AUDIO-U8+ 8)
(DEFCONSTANT +AUDIO-S8+ 32776)
(DEFCONSTANT +AUDIO-U16-LSB+ 16)
(DEFCONSTANT +AUDIO-S16-LSB+ 32784)
(DEFCONSTANT +AUDIO-U16-MSB+ 4112)
(DEFCONSTANT +AUDIO-S16-MSB+ 36880)
(DEFCONSTANT +AUDIO-U16+ 16)
(DEFCONSTANT +AUDIO-S16+ 32784)
(CFFI:DEFCSTRUCT AUDIO-CVT (NEEDED :INT) (SRC_FORMAT :UNSIGNED-SHORT)
                 (DST_FORMAT :UNSIGNED-SHORT) (RATE_INCR :DOUBLE)
                 (BUF :POINTER) (LEN :INT) (LEN_CVT :INT) (LEN_MULT :INT)
                 (LEN_RATIO :DOUBLE) (FILTERS :POINTER) (FILTER_INDEX :INT))
(CFFI:DEFCFUN ("SDL_AudioInit" AUDIO-INIT) :INT (DRIVER_NAME :STRING))
(CFFI:DEFCFUN ("SDL_AudioQuit" AUDIO-QUIT) :VOID)
(CFFI:DEFCFUN ("SDL_AudioDriverName" AUDIO-DRIVER-NAME) :STRING
  (NAMEBUF :STRING) (MAXLEN :INT))
(CFFI:DEFCFUN ("SDL_OpenAudio" OPEN-AUDIO) :INT (DESIRED :POINTER)
              (OBTAINED :POINTER))
(CFFI:DEFCENUM AUDIOSTATUS (:AUDIO-STOPPED 0) :AUDIO-PLAYING :AUDIO-PAUSED)
(CFFI:DEFCFUN ("SDL_GetAudioStatus" GET-AUDIO-STATUS) AUDIOSTATUS)
(CFFI:DEFCFUN ("SDL_PauseAudio" PAUSE-AUDIO) :VOID (PAUSE_ON :INT))
(CFFI:DEFCFUN ("SDL_LoadWAV_RW" LOAD-WAV-RW) :POINTER (SRC :POINTER)
              (FREESRC :INT) (SPEC :POINTER) (AUDIO_BUF :POINTER)
              (AUDIO_LEN :POINTER))
(CFFI:DEFCFUN ("SDL_FreeWAV" FREE-WAV) :VOID (AUDIO_BUF :POINTER))
(CFFI:DEFCFUN ("SDL_BuildAudioCVT" BUILD-AUDIO-CVT) :INT (CVT :POINTER)
              (SRC_FORMAT :UNSIGNED-SHORT) (SRC_CHANNELS :UNSIGNED-CHAR)
              (SRC_RATE :INT) (DST_FORMAT :UNSIGNED-SHORT)
              (DST_CHANNELS :UNSIGNED-CHAR) (DST_RATE :INT))
(CFFI:DEFCFUN ("SDL_ConvertAudio" CONVERT-AUDIO) :INT (CVT :POINTER))
(DEFCONSTANT +MIX-MAXVOLUME+ 128)
(CFFI:DEFCFUN ("SDL_MixAudio" MIX-AUDIO) :VOID (DST :POINTER) (SRC :POINTER)
              (LEN :UNSIGNED-INT) (VOLUME :INT))
(CFFI:DEFCFUN ("SDL_LockAudio" LOCK-AUDIO) :VOID)
(CFFI:DEFCFUN ("SDL_UnlockAudio" UNLOCK-AUDIO) :VOID)
(CFFI:DEFCFUN ("SDL_CloseAudio" CLOSE-AUDIO) :VOID)
(DEFCONSTANT +MAX-TRACKS+ 99)
(DEFCONSTANT +AUDIO-TRACK+ 0)
(DEFCONSTANT +DATA-TRACK+ 4)
(CFFI:DEFCENUM CD-STATUS :CD-TRAYEMPTY :CD-STOPPED :CD-PLAYING :CD-PAUSED
               (:CD-ERROR -1))
(CFFI:DEFCSTRUCT CD-TRACK (ID :UNSIGNED-CHAR) (TYPE :UNSIGNED-CHAR)
                 (UNUSED :UNSIGNED-SHORT) (LENGTH :UNSIGNED-INT)
                 (OFFSET :UNSIGNED-INT))
(CFFI:DEFCSTRUCT CD (ID :INT) (STATUS CD-STATUS) (NUMTRACKS :INT)
                 (CUR_TRACK :INT) (CUR_FRAME :INT) (TRACK :POINTER))
(CFFI:DEFCFUN ("SDL_CDNumDrives" CD-NUM-DRIVES) :INT)
(CFFI:DEFCFUN ("SDL_CDName" CD-NAME) :STRING (DRIVE :INT))
(CFFI:DEFCFUN ("SDL_CDOpen" CD-OPEN) :POINTER (DRIVE :INT))
(CFFI:DEFCFUN ("SDL_CDStatus" CD-STATUS) CD-STATUS (CDROM :POINTER))
(CFFI:DEFCFUN ("SDL_CDPlayTracks" CD-PLAY-TRACKS) :INT (CDROM :POINTER)
              (START_TRACK :INT) (START_FRAME :INT) (NTRACKS :INT)
              (NFRAMES :INT))
(CFFI:DEFCFUN ("SDL_CDPlay" CD-PLAY) :INT (CDROM :POINTER) (START :INT)
              (LENGTH :INT))
(CFFI:DEFCFUN ("SDL_CDPause" CD-PAUSE) :INT (CDROM :POINTER))
(CFFI:DEFCFUN ("SDL_CDResume" CD-RESUME) :INT (CDROM :POINTER))
(CFFI:DEFCFUN ("SDL_CDStop" CD-STOP) :INT (CDROM :POINTER))
(CFFI:DEFCFUN ("SDL_CDEject" CD-EJECT) :INT (CDROM :POINTER))
(CFFI:DEFCFUN ("SDL_CDClose" CD-CLOSE) :VOID (CDROM :POINTER))
(CFFI:DEFCFUN ("SDL_NumJoysticks" NUM-JOYSTICKS) :INT)
(CFFI:DEFCFUN ("SDL_JoystickName" JOYSTICK-NAME) :STRING (DEVICE_INDEX :INT))
(CFFI:DEFCFUN ("SDL_JoystickOpen" JOYSTICK-OPEN) :POINTER (DEVICE_INDEX :INT))
(CFFI:DEFCFUN ("SDL_JoystickOpened" JOYSTICK-OPENED) :INT (DEVICE_INDEX :INT))
(CFFI:DEFCFUN ("SDL_JoystickIndex" JOYSTICK-INDEX) :INT (JOYSTICK :POINTER))
(CFFI:DEFCFUN ("SDL_JoystickNumAxes" JOYSTICK-NUM-AXES) :INT
  (JOYSTICK :POINTER))
(CFFI:DEFCFUN ("SDL_JoystickNumBalls" JOYSTICK-NUM-BALLS) :INT
  (JOYSTICK :POINTER))
(CFFI:DEFCFUN ("SDL_JoystickNumHats" JOYSTICK-NUM-HATS) :INT
  (JOYSTICK :POINTER))
(CFFI:DEFCFUN ("SDL_JoystickNumButtons" JOYSTICK-NUM-BUTTONS) :INT
  (JOYSTICK :POINTER))
(CFFI:DEFCFUN ("SDL_JoystickUpdate" JOYSTICK-UPDATE) :VOID)
(CFFI:DEFCFUN ("SDL_JoystickEventState" JOYSTICK-EVENT-STATE) :INT (STATE :INT))
(CFFI:DEFCFUN ("SDL_JoystickGetAxis" JOYSTICK-GET-AXIS) :SHORT
  (JOYSTICK :POINTER) (AXIS :INT))
(DEFCONSTANT +HAT-CENTERED+ 0)
(DEFCONSTANT +HAT-UP+ 1)
(DEFCONSTANT +HAT-RIGHT+ 2)
(DEFCONSTANT +HAT-DOWN+ 4)
(DEFCONSTANT +HAT-LEFT+ 8)
(CFFI:DEFCFUN ("SDL_JoystickGetHat" JOYSTICK-GET-HAT) :UNSIGNED-CHAR
  (JOYSTICK :POINTER) (HAT :INT))
(CFFI:DEFCFUN ("SDL_JoystickGetBall" JOYSTICK-GET-BALL) :INT
  (JOYSTICK :POINTER) (BALL :INT) (DX :POINTER) (DY :POINTER))
(CFFI:DEFCFUN ("SDL_JoystickGetButton" JOYSTICK-GET-BUTTON) :UNSIGNED-CHAR
  (JOYSTICK :POINTER) (BUTTON :INT))
(CFFI:DEFCFUN ("SDL_JoystickClose" JOYSTICK-CLOSE) :VOID (JOYSTICK :POINTER))
(DEFCONSTANT +APPMOUSEFOCUS+ 1)
(DEFCONSTANT +APPINPUTFOCUS+ 2)
(DEFCONSTANT +APPACTIVE+ 4)
(CFFI:DEFCFUN ("SDL_GetAppState" GET-APP-STATE) :UNSIGNED-CHAR)
(CFFI:DEFCENUM SDL-KEY (:SDLK-UNKNOWN 0) (:SDLK-FIRST 0) (:SDLK-BACKSPACE 8)
               (:SDLK-TAB 9) (:SDLK-CLEAR 12) (:SDLK-RETURN 13)
               (:SDLK-PAUSE 19) (:SDLK-ESCAPE 27) (:SDLK-SPACE 32)
               (:SDLK-EXCLAIM 33) (:SDLK-QUOTEDBL 34) (:SDLK-HASH 35)
               (:SDLK-DOLLAR 36) (:SDLK-AMPERSAND 38) (:SDLK-QUOTE 39)
               (:SDLK-LEFTPAREN 40) (:SDLK-RIGHTPAREN 41) (:SDLK-ASTERISK 42)
               (:SDLK-PLUS 43) (:SDLK-COMMA 44) (:SDLK-MINUS 45)
               (:SDLK-PERIOD 46) (:SDLK-SLASH 47) (:SDLK-0 48) (:SDLK-1 49)
               (:SDLK-2 50) (:SDLK-3 51) (:SDLK-4 52) (:SDLK-5 53) (:SDLK-6 54)
               (:SDLK-7 55) (:SDLK-8 56) (:SDLK-9 57) (:SDLK-COLON 58)
               (:SDLK-SEMICOLON 59) (:SDLK-LESS 60) (:SDLK-EQUALS 61)
               (:SDLK-GREATER 62) (:SDLK-QUESTION 63) (:SDLK-AT 64)
               (:SDLK-LEFTBRACKET 91) (:SDLK-BACKSLASH 92)
               (:SDLK-RIGHTBRACKET 93) (:SDLK-CARET 94) (:SDLK-UNDERSCORE 95)
               (:SDLK-BACKQUOTE 96) (:SDLK-A 97) (:SDLK-B 98) (:SDLK-C 99)
               (:SDLK-D 100) (:SDLK-E 101) (:SDLK-F 102) (:SDLK-G 103)
               (:SDLK-H 104) (:SDLK-I 105) (:SDLK-J 106) (:SDLK-K 107)
               (:SDLK-L 108) (:SDLK-M 109) (:SDLK-N 110) (:SDLK-O 111)
               (:SDLK-P 112) (:SDLK-Q 113) (:SDLK-R 114) (:SDLK-S 115)
               (:SDLK-T 116) (:SDLK-U 117) (:SDLK-V 118) (:SDLK-W 119)
               (:SDLK-X 120) (:SDLK-Y 121) (:SDLK-Z 122) (:SDLK-DELETE 127)
               (:SDLK-WORLD-0 160) (:SDLK-WORLD-1 161) (:SDLK-WORLD-2 162)
               (:SDLK-WORLD-3 163) (:SDLK-WORLD-4 164) (:SDLK-WORLD-5 165)
               (:SDLK-WORLD-6 166) (:SDLK-WORLD-7 167) (:SDLK-WORLD-8 168)
               (:SDLK-WORLD-9 169) (:SDLK-WORLD-10 170) (:SDLK-WORLD-11 171)
               (:SDLK-WORLD-12 172) (:SDLK-WORLD-13 173) (:SDLK-WORLD-14 174)
               (:SDLK-WORLD-15 175) (:SDLK-WORLD-16 176) (:SDLK-WORLD-17 177)
               (:SDLK-WORLD-18 178) (:SDLK-WORLD-19 179) (:SDLK-WORLD-20 180)
               (:SDLK-WORLD-21 181) (:SDLK-WORLD-22 182) (:SDLK-WORLD-23 183)
               (:SDLK-WORLD-24 184) (:SDLK-WORLD-25 185) (:SDLK-WORLD-26 186)
               (:SDLK-WORLD-27 187) (:SDLK-WORLD-28 188) (:SDLK-WORLD-29 189)
               (:SDLK-WORLD-30 190) (:SDLK-WORLD-31 191) (:SDLK-WORLD-32 192)
               (:SDLK-WORLD-33 193) (:SDLK-WORLD-34 194) (:SDLK-WORLD-35 195)
               (:SDLK-WORLD-36 196) (:SDLK-WORLD-37 197) (:SDLK-WORLD-38 198)
               (:SDLK-WORLD-39 199) (:SDLK-WORLD-40 200) (:SDLK-WORLD-41 201)
               (:SDLK-WORLD-42 202) (:SDLK-WORLD-43 203) (:SDLK-WORLD-44 204)
               (:SDLK-WORLD-45 205) (:SDLK-WORLD-46 206) (:SDLK-WORLD-47 207)
               (:SDLK-WORLD-48 208) (:SDLK-WORLD-49 209) (:SDLK-WORLD-50 210)
               (:SDLK-WORLD-51 211) (:SDLK-WORLD-52 212) (:SDLK-WORLD-53 213)
               (:SDLK-WORLD-54 214) (:SDLK-WORLD-55 215) (:SDLK-WORLD-56 216)
               (:SDLK-WORLD-57 217) (:SDLK-WORLD-58 218) (:SDLK-WORLD-59 219)
               (:SDLK-WORLD-60 220) (:SDLK-WORLD-61 221) (:SDLK-WORLD-62 222)
               (:SDLK-WORLD-63 223) (:SDLK-WORLD-64 224) (:SDLK-WORLD-65 225)
               (:SDLK-WORLD-66 226) (:SDLK-WORLD-67 227) (:SDLK-WORLD-68 228)
               (:SDLK-WORLD-69 229) (:SDLK-WORLD-70 230) (:SDLK-WORLD-71 231)
               (:SDLK-WORLD-72 232) (:SDLK-WORLD-73 233) (:SDLK-WORLD-74 234)
               (:SDLK-WORLD-75 235) (:SDLK-WORLD-76 236) (:SDLK-WORLD-77 237)
               (:SDLK-WORLD-78 238) (:SDLK-WORLD-79 239) (:SDLK-WORLD-80 240)
               (:SDLK-WORLD-81 241) (:SDLK-WORLD-82 242) (:SDLK-WORLD-83 243)
               (:SDLK-WORLD-84 244) (:SDLK-WORLD-85 245) (:SDLK-WORLD-86 246)
               (:SDLK-WORLD-87 247) (:SDLK-WORLD-88 248) (:SDLK-WORLD-89 249)
               (:SDLK-WORLD-90 250) (:SDLK-WORLD-91 251) (:SDLK-WORLD-92 252)
               (:SDLK-WORLD-93 253) (:SDLK-WORLD-94 254) (:SDLK-WORLD-95 255)
               (:SDLK-KP0 256) (:SDLK-KP1 257) (:SDLK-KP2 258) (:SDLK-KP3 259)
               (:SDLK-KP4 260) (:SDLK-KP5 261) (:SDLK-KP6 262) (:SDLK-KP7 263)
               (:SDLK-KP8 264) (:SDLK-KP9 265) (:SDLK-KP-PERIOD 266)
               (:SDLK-KP-DIVIDE 267) (:SDLK-KP-MULTIPLY 268)
               (:SDLK-KP-MINUS 269) (:SDLK-KP-PLUS 270) (:SDLK-KP-ENTER 271)
               (:SDLK-KP-EQUALS 272) (:SDLK-UP 273) (:SDLK-DOWN 274)
               (:SDLK-RIGHT 275) (:SDLK-LEFT 276) (:SDLK-INSERT 277)
               (:SDLK-HOME 278) (:SDLK-END 279) (:SDLK-PAGEUP 280)
               (:SDLK-PAGEDOWN 281) (:SDLK-F1 282) (:SDLK-F2 283)
               (:SDLK-F3 284) (:SDLK-F4 285) (:SDLK-F5 286) (:SDLK-F6 287)
               (:SDLK-F7 288) (:SDLK-F8 289) (:SDLK-F9 290) (:SDLK-F10 291)
               (:SDLK-F11 292) (:SDLK-F12 293) (:SDLK-F13 294) (:SDLK-F14 295)
               (:SDLK-F15 296) (:SDLK-NUMLOCK 300) (:SDLK-CAPSLOCK 301)
               (:SDLK-SCROLLOCK 302) (:SDLK-RSHIFT 303) (:SDLK-LSHIFT 304)
               (:SDLK-RCTRL 305) (:SDLK-LCTRL 306) (:SDLK-RALT 307)
               (:SDLK-LALT 308) (:SDLK-RMETA 309) (:SDLK-LMETA 310)
               (:SDLK-LSUPER 311) (:SDLK-RSUPER 312) (:SDLK-MODE 313)
               (:SDLK-COMPOSE 314) (:SDLK-HELP 315) (:SDLK-PRINT 316)
               (:SDLK-SYSREQ 317) (:SDLK-BREAK 318) (:SDLK-MENU 319)
               (:SDLK-POWER 320) (:SDLK-EURO 321) (:SDLK-UNDO 322) :SDLK-LAST)
(CFFI:DEFCENUM SDL-MOD (:KMOD-NONE 0) (:KMOD-LSHIFT 1) (:KMOD-RSHIFT 2)
               (:KMOD-LCTRL 64) (:KMOD-RCTRL 128) (:KMOD-LALT 256)
               (:KMOD-RALT 512) (:KMOD-LMETA 1024) (:KMOD-RMETA 2048)
               (:KMOD-NUM 4096) (:KMOD-CAPS 8192) (:KMOD-MODE 16384)
               (:KMOD-RESERVED 32768))
(CFFI:DEFCSTRUCT KEYSYM (SCANCODE :UNSIGNED-CHAR) (SYM SDL-KEY) (MOD SDL-MOD)
                 (UNICODE :UNSIGNED-SHORT))
(DEFCONSTANT +ALL-HOTKEYS+ 4294967295)
(CFFI:DEFCFUN ("SDL_EnableUNICODE" ENABLE-UNICODE) :INT (ENABLE :INT))
(DEFCONSTANT +DEFAULT-REPEAT-DELAY+ 500)
(DEFCONSTANT +DEFAULT-REPEAT-INTERVAL+ 30)
(CFFI:DEFCFUN ("SDL_EnableKeyRepeat" ENABLE-KEY-REPEAT) :INT (DELAY :INT)
              (INTERVAL :INT))
(CFFI:DEFCFUN ("SDL_GetKeyRepeat" GET-KEY-REPEAT) :VOID (DELAY :POINTER)
              (INTERVAL :POINTER))
(CFFI:DEFCFUN ("SDL_GetKeyState" GET-KEY-STATE) :POINTER (NUMKEYS :POINTER))
(CFFI:DEFCFUN ("SDL_GetModState" GET-MOD-STATE) SDL-MOD)
(CFFI:DEFCFUN ("SDL_SetModState" SET-MOD-STATE) :VOID (MODSTATE SDL-MOD))
(CFFI:DEFCFUN ("SDL_GetKeyName" GET-KEY-NAME) :STRING (KEY SDL-KEY))
(CFFI:DEFCSTRUCT CURSOR (AREA :POINTER) (HOT_X :SHORT) (HOT_Y :SHORT)
                 (DATA :POINTER) (MASK :POINTER) (SAVE :POINTER)
                 (WM_CURSOR :POINTER))
(CFFI:DEFCFUN ("SDL_GetMouseState" GET-MOUSE-STATE) :UNSIGNED-CHAR (X :POINTER)
              (Y :POINTER))
(CFFI:DEFCFUN ("SDL_GetRelativeMouseState" GET-RELATIVE-MOUSE-STATE)
    :UNSIGNED-CHAR (X :POINTER) (Y :POINTER))
(CFFI:DEFCFUN ("SDL_WarpMouse" WARP-MOUSE) :VOID (X :UNSIGNED-SHORT)
              (Y :UNSIGNED-SHORT))
(CFFI:DEFCFUN ("SDL_CreateCursor" CREATE-CURSOR) :POINTER (DATA :POINTER)
              (MASK :POINTER) (W :INT) (H :INT) (HOT_X :INT) (HOT_Y :INT))
(CFFI:DEFCFUN ("SDL_SetCursor" SET-CURSOR) :VOID (CURSOR :POINTER))
(CFFI:DEFCFUN ("SDL_GetCursor" GET-CURSOR) :POINTER)
(CFFI:DEFCFUN ("SDL_FreeCursor" FREE-CURSOR) :VOID (CURSOR :POINTER))
(CFFI:DEFCFUN ("SDL_ShowCursor" SHOW-CURSOR) :INT (TOGGLE :INT))
(DEFCONSTANT +BUTTON-LEFT+ 1)
(DEFCONSTANT +BUTTON-MIDDLE+ 2)
(DEFCONSTANT +BUTTON-RIGHT+ 3)
(DEFCONSTANT +BUTTON-WHEELUP+ 4)
(DEFCONSTANT +BUTTON-WHEELDOWN+ 5)
(DEFCONSTANT +RELEASED+ 0)
(DEFCONSTANT +PRESSED+ 1)
(CFFI:DEFCENUM EVENT-TYPE (:NOEVENT 0) :ACTIVEEVENT :KEYDOWN :KEYUP
               :MOUSEMOTION :MOUSEBUTTONDOWN :MOUSEBUTTONUP :JOYAXISMOTION
               :JOYBALLMOTION :JOYHATMOTION :JOYBUTTONDOWN :JOYBUTTONUP :QUIT
               :SYSWMEVENT :EVENT-RESERVEDA :EVENT-RESERVEDB :VIDEORESIZE
               :VIDEOEXPOSE :EVENT-RESERVED2 :EVENT-RESERVED3 :EVENT-RESERVED4
               :EVENT-RESERVED5 :EVENT-RESERVED6 :EVENT-RESERVED7
               (:USEREVENT 24) (:NUMEVENTS 32))
(DEFCONSTANT +ALLEVENTS+ 4294967295)
(CFFI:DEFCSTRUCT ACTIVE-EVENT (TYPE :UNSIGNED-CHAR) (GAIN :UNSIGNED-CHAR)
                 (STATE :UNSIGNED-CHAR))
(CFFI:DEFCSTRUCT KEYBOARD-EVENT (TYPE :UNSIGNED-CHAR) (WHICH :UNSIGNED-CHAR)
                 (STATE :UNSIGNED-CHAR) (KEYSYM KEYSYM))
(CFFI:DEFCSTRUCT MOUSE-MOTION-EVENT (TYPE :UNSIGNED-CHAR)
                 (WHICH :UNSIGNED-CHAR) (STATE :UNSIGNED-CHAR)
                 (X :UNSIGNED-SHORT) (Y :UNSIGNED-SHORT) (XREL :SHORT)
                 (YREL :SHORT))
(CFFI:DEFCSTRUCT MOUSE-BUTTON-EVENT (TYPE :UNSIGNED-CHAR)
                 (WHICH :UNSIGNED-CHAR) (BUTTON :UNSIGNED-CHAR)
                 (STATE :UNSIGNED-CHAR) (X :UNSIGNED-SHORT) (Y :UNSIGNED-SHORT))
(CFFI:DEFCSTRUCT JOY-AXIS-EVENT (TYPE :UNSIGNED-CHAR) (WHICH :UNSIGNED-CHAR)
                 (AXIS :UNSIGNED-CHAR) (VALUE :SHORT))
(CFFI:DEFCSTRUCT JOY-BALL-EVENT (TYPE :UNSIGNED-CHAR) (WHICH :UNSIGNED-CHAR)
                 (BALL :UNSIGNED-CHAR) (XREL :SHORT) (YREL :SHORT))
(CFFI:DEFCSTRUCT JOY-HAT-EVENT (TYPE :UNSIGNED-CHAR) (WHICH :UNSIGNED-CHAR)
                 (HAT :UNSIGNED-CHAR) (VALUE :UNSIGNED-CHAR))
(CFFI:DEFCSTRUCT JOY-BUTTON-EVENT (TYPE :UNSIGNED-CHAR) (WHICH :UNSIGNED-CHAR)
                 (BUTTON :UNSIGNED-CHAR) (STATE :UNSIGNED-CHAR))
(CFFI:DEFCSTRUCT RESIZE-EVENT (TYPE :UNSIGNED-CHAR) (W :INT) (H :INT))
(CFFI:DEFCSTRUCT EXPOSE-EVENT (TYPE :UNSIGNED-CHAR))
(CFFI:DEFCSTRUCT QUIT-EVENT (TYPE :UNSIGNED-CHAR))
(CFFI:DEFCSTRUCT USER-EVENT (TYPE :UNSIGNED-CHAR) (CODE :INT) (DATA1 :POINTER)
                 (DATA2 :POINTER))
(CFFI:DEFCSTRUCT SYS-WM-EVENT (TYPE :UNSIGNED-CHAR) (MSG :POINTER))
(CFFI:DEFCUNION EVENT (TYPE :UNSIGNED-CHAR) (ACTIVE ACTIVE-EVENT)
                (KEY KEYBOARD-EVENT) (MOTION MOUSE-MOTION-EVENT)
                (BUTTON MOUSE-BUTTON-EVENT) (JAXIS JOY-AXIS-EVENT)
                (JBALL JOY-BALL-EVENT) (JHAT JOY-HAT-EVENT)
                (JBUTTON JOY-BUTTON-EVENT) (RESIZE RESIZE-EVENT)
                (EXPOSE EXPOSE-EVENT) (QUIT QUIT-EVENT) (USER USER-EVENT)
                (SYSWM SYS-WM-EVENT))
(CFFI:DEFCFUN ("SDL_PumpEvents" PUMP-EVENTS) :VOID)
(CFFI:DEFCENUM EVENTACTION :ADDEVENT :PEEKEVENT :GETEVENT)
(CFFI:DEFCFUN ("SDL_PeepEvents" PEEP-EVENTS) :INT (EVENTS :POINTER)
              (NUMEVENTS :INT) (ACTION EVENTACTION) (MASK :UNSIGNED-INT))
(CFFI:DEFCFUN ("SDL_PollEvent" POLL-EVENT) :INT (EVENT :POINTER))
(CFFI:DEFCFUN ("SDL_WaitEvent" WAIT-EVENT) :INT (EVENT :POINTER))
(CFFI:DEFCFUN ("SDL_PushEvent" PUSH-EVENT) :INT (EVENT :POINTER))
(CFFI:DEFCFUN ("SDL_SetEventFilter" SET-EVENT-FILTER) :VOID (FILTER :POINTER))
(CFFI:DEFCFUN ("SDL_GetEventFilter" GET-EVENT-FILTER) :POINTER)
(DEFCONSTANT +QUERY+ -1)
(DEFCONSTANT +IGNORE+ 0)
(DEFCONSTANT +DISABLE+ 0)
(DEFCONSTANT +ENABLE+ 1)
(CFFI:DEFCFUN ("SDL_EventState" EVENT-STATE) :UNSIGNED-CHAR
  (TYPE :UNSIGNED-CHAR) (STATE :INT))
(DEFCONSTANT +ALPHA-OPAQUE+ 255)
(DEFCONSTANT +ALPHA-TRANSPARENT+ 0)
(CFFI:DEFCSTRUCT RECT (X :SHORT) (Y :SHORT) (W :UNSIGNED-SHORT)
                 (H :UNSIGNED-SHORT))
(CFFI:DEFCSTRUCT COLOR (R :UNSIGNED-CHAR) (G :UNSIGNED-CHAR) (B :UNSIGNED-CHAR)
                 (UNUSED :UNSIGNED-CHAR))
(CFFI:DEFCSTRUCT PALETTE (NCOLORS :INT) (COLORS :POINTER))
(CFFI:DEFCSTRUCT PIXEL-FORMAT (PALETTE :POINTER) (BITSPERPIXEL :UNSIGNED-CHAR)
                 (BYTESPERPIXEL :UNSIGNED-CHAR) (RLOSS :UNSIGNED-CHAR)
                 (GLOSS :UNSIGNED-CHAR) (BLOSS :UNSIGNED-CHAR)
                 (ALOSS :UNSIGNED-CHAR) (RSHIFT :UNSIGNED-CHAR)
                 (GSHIFT :UNSIGNED-CHAR) (BSHIFT :UNSIGNED-CHAR)
                 (ASHIFT :UNSIGNED-CHAR) (RMASK :UNSIGNED-INT)
                 (GMASK :UNSIGNED-INT) (BMASK :UNSIGNED-INT)
                 (AMASK :UNSIGNED-INT) (COLORKEY :UNSIGNED-INT)
                 (ALPHA :UNSIGNED-CHAR))
(CFFI:DEFCSTRUCT SURFACE (FLAGS :UNSIGNED-INT) (FORMAT :POINTER) (W :INT)
                 (H :INT) (PITCH :UNSIGNED-SHORT) (PIXELS :POINTER)
                 (OFFSET :INT) (HWDATA :POINTER) (CLIP_RECT RECT)
                 (UNUSED1 :UNSIGNED-INT) (LOCKED :UNSIGNED-INT) (MAP :POINTER)
                 (FORMAT_VERSION :UNSIGNED-INT) (REFCOUNT :INT))
(DEFCONSTANT +SWSURFACE+ 0)
(DEFCONSTANT +HWSURFACE+ 1)
(DEFCONSTANT +ASYNCBLIT+ 4)
(DEFCONSTANT +ANYFORMAT+ 268435456)
(DEFCONSTANT +HWPALETTE+ 536870912)
(DEFCONSTANT +DOUBLEBUF+ 1073741824)
(DEFCONSTANT +FULLSCREEN+ 2147483648)
(DEFCONSTANT +OPENGL+ 2)
(DEFCONSTANT +OPENGLBLIT+ 10)
(DEFCONSTANT +RESIZABLE+ 16)
(DEFCONSTANT +NOFRAME+ 32)
(DEFCONSTANT +HWACCEL+ 256)
(DEFCONSTANT +SRCCOLORKEY+ 4096)
(DEFCONSTANT +RLEACCELOK+ 8192)
(DEFCONSTANT +RLEACCEL+ 16384)
(DEFCONSTANT +SRCALPHA+ 65536)
(DEFCONSTANT +PREALLOC+ 16777216)
(DEFCONSTANT +YV12-OVERLAY+ 842094169)
(DEFCONSTANT +IYUV-OVERLAY+ 1448433993)
(DEFCONSTANT +YUY2-OVERLAY+ 844715353)
(DEFCONSTANT +UYVY-OVERLAY+ 1498831189)
(DEFCONSTANT +YVYU-OVERLAY+ 1431918169)
(CFFI:DEFCSTRUCT OVERLAY (FORMAT :UNSIGNED-INT) (W :INT) (H :INT) (PLANES :INT)
                 (PITCHES :POINTER) (PIXELS :POINTER) (HWFUNCS :POINTER)
                 (HWDATA :POINTER) (HW_OVERLAY :UNSIGNED-INT)
                 (UNUSEDBITS :UNSIGNED-INT))
(CFFI:DEFCENUM GL-ATTR :GL-RED-SIZE :GL-GREEN-SIZE :GL-BLUE-SIZE :GL-ALPHA-SIZE
               :GL-BUFFER-SIZE :GL-DOUBLEBUFFER :GL-DEPTH-SIZE :GL-STENCIL-SIZE
               :GL-ACCUM-RED-SIZE :GL-ACCUM-GREEN-SIZE :GL-ACCUM-BLUE-SIZE
               :GL-ACCUM-ALPHA-SIZE :GL-STEREO :GL-MULTISAMPLEBUFFERS
               :GL-MULTISAMPLESAMPLES :GL-ACCELERATED-VISUAL :GL-SWAP-CONTROL)
(DEFCONSTANT +LOGPAL+ 1)
(DEFCONSTANT +PHYSPAL+ 2)
(CFFI:DEFCFUN ("SDL_VideoInit" VIDEO-INIT) :INT (DRIVER_NAME :STRING)
              (FLAGS :UNSIGNED-INT))
(CFFI:DEFCFUN ("SDL_VideoQuit" VIDEO-QUIT) :VOID)
(CFFI:DEFCFUN ("SDL_VideoDriverName" VIDEO-DRIVER-NAME) :STRING
  (NAMEBUF :STRING) (MAXLEN :INT))
(CFFI:DEFCFUN ("SDL_GetVideoSurface" GET-VIDEO-SURFACE) :POINTER)
(CFFI:DEFCFUN ("SDL_GetVideoInfo" GET-VIDEO-INFO) :POINTER)
(CFFI:DEFCFUN ("SDL_VideoModeOK" VIDEO-MODE-OK) :INT (WIDTH :INT) (HEIGHT :INT)
              (BPP :INT) (FLAGS :UNSIGNED-INT))
(CFFI:DEFCFUN ("SDL_ListModes" LIST-MODES) :POINTER (FORMAT :POINTER)
              (FLAGS :UNSIGNED-INT))
(CFFI:DEFCFUN ("SDL_SetVideoMode" SET-VIDEO-MODE) :POINTER (WIDTH :INT)
              (HEIGHT :INT) (BPP :INT) (FLAGS :UNSIGNED-INT))
(CFFI:DEFCFUN ("SDL_UpdateRects" UPDATE-RECTS) :VOID (SCREEN :POINTER)
              (NUMRECTS :INT) (RECTS :POINTER))
(CFFI:DEFCFUN ("SDL_UpdateRect" UPDATE-RECT) :VOID (SCREEN :POINTER) (X :INT)
              (Y :INT) (W :UNSIGNED-INT) (H :UNSIGNED-INT))
(CFFI:DEFCFUN ("SDL_Flip" FLIP) :INT (SCREEN :POINTER))
(CFFI:DEFCFUN ("SDL_SetGamma" SET-GAMMA) :INT (RED :FLOAT) (GREEN :FLOAT)
              (BLUE :FLOAT))
(CFFI:DEFCFUN ("SDL_SetGammaRamp" SET-GAMMA-RAMP) :INT (RED :POINTER)
              (GREEN :POINTER) (BLUE :POINTER))
(CFFI:DEFCFUN ("SDL_GetGammaRamp" GET-GAMMA-RAMP) :INT (RED :POINTER)
              (GREEN :POINTER) (BLUE :POINTER))
(CFFI:DEFCFUN ("SDL_SetColors" SET-COLORS) :INT (SURFACE :POINTER)
              (COLORS :POINTER) (FIRSTCOLOR :INT) (NCOLORS :INT))
(CFFI:DEFCFUN ("SDL_SetPalette" SET-PALETTE) :INT (SURFACE :POINTER)
              (FLAGS :INT) (COLORS :POINTER) (FIRSTCOLOR :INT) (NCOLORS :INT))
(CFFI:DEFCFUN ("SDL_MapRGB" MAP-RGB) :UNSIGNED-INT (FORMAT :POINTER)
              (R :UNSIGNED-CHAR) (G :UNSIGNED-CHAR) (B :UNSIGNED-CHAR))
(CFFI:DEFCFUN ("SDL_MapRGBA" MAP-RGBA) :UNSIGNED-INT (FORMAT :POINTER)
              (R :UNSIGNED-CHAR) (G :UNSIGNED-CHAR) (B :UNSIGNED-CHAR)
              (A :UNSIGNED-CHAR))
(CFFI:DEFCFUN ("SDL_GetRGB" GET-RGB) :VOID (PIXEL :UNSIGNED-INT) (FMT :POINTER)
              (R :POINTER) (G :POINTER) (B :POINTER))
(CFFI:DEFCFUN ("SDL_GetRGBA" GET-RGBA) :VOID (PIXEL :UNSIGNED-INT)
              (FMT :POINTER) (R :POINTER) (G :POINTER) (B :POINTER)
              (A :POINTER))
(CFFI:DEFCFUN ("SDL_CreateRGBSurface" CREATE-RGB-SURFACE) :POINTER
  (FLAGS :UNSIGNED-INT) (WIDTH :INT) (HEIGHT :INT) (DEPTH :INT)
  (RMASK :UNSIGNED-INT) (GMASK :UNSIGNED-INT) (BMASK :UNSIGNED-INT)
  (AMASK :UNSIGNED-INT))
(CFFI:DEFCFUN ("SDL_CreateRGBSurfaceFrom" CREATE-RGB-SURFACE-FROM) :POINTER
  (PIXELS :POINTER) (WIDTH :INT) (HEIGHT :INT) (DEPTH :INT)
  (PITCH :INT) (RMASK :UNSIGNED-INT) (GMASK :UNSIGNED-INT)
  (BMASK :UNSIGNED-INT) (AMASK :UNSIGNED-INT))
(CFFI:DEFCFUN ("SDL_FreeSurface" FREE-SURFACE) :VOID (SURFACE :POINTER))
(CFFI:DEFCFUN ("SDL_LockSurface" LOCK-SURFACE) :INT (SURFACE :POINTER))
(CFFI:DEFCFUN ("SDL_UnlockSurface" UNLOCK-SURFACE) :VOID (SURFACE :POINTER))
(CFFI:DEFCFUN ("SDL_LoadBMP_RW" LOAD-BMP-RW) :POINTER (SRC :POINTER)
              (FREESRC :INT))
(CFFI:DEFCFUN ("SDL_SaveBMP_RW" SAVE-BMP-RW) :INT (SURFACE :POINTER)
              (DST :POINTER) (FREEDST :INT))
(CFFI:DEFCFUN ("SDL_SetColorKey" SET-COLOR-KEY) :INT (SURFACE :POINTER)
              (FLAG :UNSIGNED-INT) (KEY :UNSIGNED-INT))
(CFFI:DEFCFUN ("SDL_SetAlpha" SET-ALPHA) :INT (SURFACE :POINTER)
              (FLAG :UNSIGNED-INT) (ALPHA :UNSIGNED-CHAR))
(CFFI:DEFCFUN ("SDL_SetClipRect" SET-CLIP-RECT) :POINTER (SURFACE :POINTER)
              (RECT :POINTER))
(CFFI:DEFCFUN ("SDL_GetClipRect" GET-CLIP-RECT) :VOID (SURFACE :POINTER)
              (RECT :POINTER))
(CFFI:DEFCFUN ("SDL_ConvertSurface" CONVERT-SURFACE) :POINTER (SRC :POINTER)
              (FMT :POINTER) (FLAGS :UNSIGNED-INT))
(CFFI:DEFCFUN ("SDL_UpperBlit" UPPER-BLIT) :INT (SRC :POINTER)
              (SRCRECT :POINTER) (DST :POINTER) (DSTRECT :POINTER))
(CFFI:DEFCFUN ("SDL_LowerBlit" LOWER-BLIT) :INT (SRC :POINTER)
              (SRCRECT :POINTER) (DST :POINTER) (DSTRECT :POINTER))
(CFFI:DEFCFUN ("SDL_FillRect" FILL-RECT) :INT (DST :POINTER) (DSTRECT :POINTER)
              (COLOR :UNSIGNED-INT))
(CFFI:DEFCFUN ("SDL_DisplayFormat" DISPLAY-FORMAT) :POINTER (SURFACE :POINTER))
(CFFI:DEFCFUN ("SDL_DisplayFormatAlpha" DISPLAY-FORMAT-ALPHA) :POINTER
  (SURFACE :POINTER))
(CFFI:DEFCFUN ("SDL_CreateYUVOverlay" CREATE-YUV-OVERLAY) :POINTER (WIDTH :INT)
              (HEIGHT :INT) (FORMAT :UNSIGNED-INT) (DISPLAY :POINTER))
(CFFI:DEFCFUN ("SDL_LockYUVOverlay" LOCK-YUV-OVERLAY) :INT (OVERLAY :POINTER))
(CFFI:DEFCFUN ("SDL_UnlockYUVOverlay" UNLOCK-YUV-OVERLAY) :VOID
  (OVERLAY :POINTER))
(CFFI:DEFCFUN ("SDL_DisplayYUVOverlay" DISPLAY-YUV-OVERLAY) :INT
  (OVERLAY :POINTER) (DSTRECT :POINTER))
(CFFI:DEFCFUN ("SDL_FreeYUVOverlay" FREE-YUV-OVERLAY) :VOID (OVERLAY :POINTER))
(CFFI:DEFCFUN ("SDL_GL_LoadLibrary" GL-LOAD-LIBRARY) :INT (PATH :STRING))
(CFFI:DEFCFUN ("SDL_GL_GetProcAddress" GL-GET-PROC-ADDRESS) :POINTER
  (PROC :STRING))
(CFFI:DEFCFUN ("SDL_GL_SetAttribute" GL-SET-ATTRIBUTE) :INT (ATTR GL-ATTR)
              (VALUE :INT))
(CFFI:DEFCFUN ("SDL_GL_GetAttribute" GL-GET-ATTRIBUTE) :INT (ATTR GL-ATTR)
              (VALUE :POINTER))
(CFFI:DEFCFUN ("SDL_GL_SwapBuffers" GL-SWAP-BUFFERS) :VOID)
(CFFI:DEFCFUN ("SDL_GL_UpdateRects" GL-UPDATE-RECTS) :VOID (NUMRECTS :INT)
              (RECTS :POINTER))
(CFFI:DEFCFUN ("SDL_GL_Lock" GL-LOCK) :VOID)
(CFFI:DEFCFUN ("SDL_GL_Unlock" GL-UNLOCK) :VOID)
(CFFI:DEFCFUN ("SDL_WM_SetCaption" WM-SET-CAPTION) :VOID (TITLE :STRING)
              (ICON :STRING))
(CFFI:DEFCFUN ("SDL_WM_GetCaption" WM-GET-CAPTION) :VOID (TITLE :POINTER)
              (ICON :POINTER))
(CFFI:DEFCFUN ("SDL_WM_SetIcon" WM-SET-ICON) :VOID (ICON :POINTER)
              (MASK :POINTER))
(CFFI:DEFCFUN ("SDL_WM_IconifyWindow" WM-ICONIFY-WINDOW) :INT)
(CFFI:DEFCFUN ("SDL_WM_ToggleFullScreen" WM-TOGGLE-FULL-SCREEN) :INT
  (SURFACE :POINTER))
(CFFI:DEFCENUM GRAB-MODE (:GRAB-QUERY -1) (:GRAB-OFF 0) (:GRAB-ON 1)
               :GRAB-FULLSCREEN)
(CFFI:DEFCFUN ("SDL_WM_GrabInput" WM-GRAB-INPUT) GRAB-MODE (MODE GRAB-MODE))
(CFFI:DEFCFUN ("SDL_SoftStretch" SOFT-STRETCH) :INT (SRC :POINTER)
              (SRCRECT :POINTER) (DST :POINTER) (DSTRECT :POINTER))
(DEFCONSTANT +MAJOR-VERSION+ 1)
(DEFCONSTANT +MINOR-VERSION+ 2)
(DEFCONSTANT +PATCHLEVEL+ 10)
(CFFI:DEFCSTRUCT VERSION (MAJOR :UNSIGNED-CHAR) (MINOR :UNSIGNED-CHAR)
                 (PATCH :UNSIGNED-CHAR))
(CFFI:DEFCFUN ("SDL_Linked_Version" LINKED-VERSION) :POINTER)
(DEFCONSTANT +INIT-TIMER+ 1)
(DEFCONSTANT +INIT-AUDIO+ 16)
(DEFCONSTANT +INIT-VIDEO+ 32)
(DEFCONSTANT +INIT-CD-ROM+ 256)
(DEFCONSTANT +INIT-JOYSTICK+ 512)
(DEFCONSTANT +INIT-NOPARACHUTE+ 1048576)
(DEFCONSTANT +INIT-EVENTTHREAD+ 16777216)
(DEFCONSTANT +INIT-EVERYTHING+ 65535)
(CFFI:DEFCFUN ("SDL_Init" INIT) :INT (FLAGS :UNSIGNED-INT))
(CFFI:DEFCFUN ("SDL_InitSubSystem" INIT-SUB-SYSTEM) :INT (FLAGS :UNSIGNED-INT))
(CFFI:DEFCFUN ("SDL_QuitSubSystem" QUIT-SUB-SYSTEM) :VOID (FLAGS :UNSIGNED-INT))
(CFFI:DEFCFUN ("SDL_WasInit" WAS-INIT) :UNSIGNED-INT (FLAGS :UNSIGNED-INT))
(CFFI:DEFCFUN ("SDL_Quit" QUIT) :VOID)
