;;;;
;;;; system-constants.lisp
;;;;
;;;; Copyright (C) 2006-2007, Jack D. Unrue
;;;; All rights reserved.
;;;;
;;;; Redistribution and use in source and binary forms, with or without
;;;; modification, are permitted provided that the following conditions
;;;; are met:
;;;; 
;;;;     1. Redistributions of source code must retain the above copyright
;;;;        notice, this list of conditions and the following disclaimer.
;;;; 
;;;;     2. Redistributions in binary form must reproduce the above copyright
;;;;        notice, this list of conditions and the following disclaimer in the
;;;;        documentation and/or other materials provided with the distribution.
;;;; 
;;;;     3. Neither the names of the authors nor the names of its contributors
;;;;        may be used to endorse or promote products derived from this software
;;;;        without specific prior written permission.
;;;; 
;;;; THIS SOFTWARE IS PROVIDED BY THE AUTHORS AND CONTRIBUTORS "AS IS" AND ANY
;;;; EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
;;;; WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DIS-
;;;; CLAIMED.  IN NO EVENT SHALL THE AUTHORS AND CONTRIBUTORS BE LIABLE FOR ANY
;;;; DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
;;;; (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
;;;; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
;;;; ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
;;;; (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
;;;; SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
;;;;

(in-package :graphic-forms.uitoolkit.system)

;;;
;;; registered message names
;;;
(defparameter *lbselchstringa*       "commdlg_LBSelChangedNotify")
(defparameter *sharevistringa*           "commdlg_ShareViolation")
(defparameter *fileokstringa*                "commdlg_FileNameOK")
(defparameter *colorokstringa*                  "commdlg_ColorOK")
(defparameter *setrgbstringa*               "commdlg_SetRGBColor")
(defparameter *helpmsgstringa*                     "commdlg_help")
(defparameter *findmsgstringa*              "commdlg_FindReplace")

(defconstant +wm-user+                     #x0400)
(defconstant +wm-app+                      #x8000)

(defconstant +wm-job-posting+              #x2112)

(defconstant +ad-counterclockwise+              1)
(defconstant +ad-clockwise+                     2)

(defconstant +arw-bottomleft+              #x0000)
(defconstant +arw-bottomright+             #x0001)
(defconstant +arw-topleft+                 #x0002)
(defconstant +arw-topright+                #x0003)
(defconstant +arw-startmask+               #x0003)
(defconstant +arw-startright+              #x0001)
(defconstant +arw-starttop+                #x0002)

(defconstant +arw-left+                    #x0000)
(defconstant +arw-right+                   #x0000)
(defconstant +arw-up+                      #x0004)
(defconstant +arw-down+                    #x0004)
(defconstant +arw-hide+                    #x0008)

(defconstant +bi-rgb+                           0)
(defconstant +bi-rle8+                          1)
(defconstant +bi-rle4+                          2)
(defconstant +bi-bitfields+                     3)
(defconstant +bi-jpeg+                          4)
(defconstant +bi-png+                           5)

(defconstant +blt-blackness+           #x00000042)
(defconstant +blt-notsrcerase+         #x001100A6)
(defconstant +blt-notsrccopy+          #x00330008)
(defconstant +blt-srcerase+            #x00440328)
(defconstant +blt-dstinvert+           #x00550009)
(defconstant +blt-patinvert+           #x005A0049)
(defconstant +blt-srcinvert+           #x00660046)
(defconstant +blt-srcand+              #x008800C6)
(defconstant +blt-mergecopy+           #x00C000CA)
(defconstant +blt-mergepaint+          #x00BB0226)
(defconstant +blt-srccopy+             #x00CC0020)
(defconstant +blt-srcpaint+            #x00EE0086)
(defconstant +blt-patcopy+             #x00F00021)
(defconstant +blt-patpaint+            #x00FB0A09)
(defconstant +blt-whiteness+           #x00FF0062)
(defconstant +blt-captureblt+          #x40000000)
(defconstant +blt-nomirrorbitmap+      #x80000000)

(defconstant +bm-getcheck+                 #x00F0)
(defconstant +bm-setcheck+                 #x00F1)
(defconstant +bm-getstate+                 #x00F2)
(defconstant +bm-setstate+                 #x00F3)
(defconstant +bm-setstyle+                 #x00F4)
(defconstant +bm-click+                    #x00F5)
(defconstant +bm-getimage+                 #x00F6)
(defconstant +bm-setimage+                 #x00F7)

(defconstant +bs-solid+                         0)
(defconstant +bs-null+                          1)
(defconstant +bs-hollow+                        1)
(defconstant +bs-hatched+                       2)
(defconstant +bs-pattern+                       3)
(defconstant +bs-indexed+                       4)
(defconstant +bs-dibpattern+                    5)
(defconstant +bs-dibpatternpt+                  6)
(defconstant +bs-pattern8x8+                    7)
(defconstant +bs-dibpattern8x8+                 8)
(defconstant +bs-monopattern+                   9)

(defconstant +bs-pushbutton+           #x00000000)
(defconstant +bs-defpushbutton+        #x00000001)
(defconstant +bs-checkbox+             #x00000002)
(defconstant +bs-autocheckbox+         #x00000003)
(defconstant +bs-radiobutton+          #x00000004)
(defconstant +bs-3state+               #x00000005)
(defconstant +bs-auto3state+           #x00000006)
(defconstant +bs-groupbox+             #x00000007)
(defconstant +bs-userbutton+           #x00000008)
(defconstant +bs-autoradiobutton+      #x00000009)
(defconstant +bs-pushbox+              #x0000000A)
(defconstant +bs-ownerdraw+            #x0000000B)
(defconstant +bs-typemask+             #x0000000F)
(defconstant +bs-lefttext+             #x00000020)
(defconstant +bs-text+                 #x00000000)
(defconstant +bs-icon+                 #x00000040)
(defconstant +bs-bitmap+               #x00000080)
(defconstant +bs-left+                 #x00000100)
(defconstant +bs-right+                #x00000200)
(defconstant +bs-center+               #x00000300)
(defconstant +bs-top+                  #x00000400)
(defconstant +bs-bottom+               #x00000800)
(defconstant +bs-vcenter+              #x00000C00)
(defconstant +bs-pushlike+             #x00001000)
(defconstant +bs-multiline+            #x00002000)
(defconstant +bs-notify+               #x00004000)
(defconstant +bs-flat+                 #x00008000)
(defconstant +bs-rightbutton+          #x00000020)

(defconstant +bst-unchecked+               #x0000)
(defconstant +bst-checked+                 #x0001)
(defconstant +bst-indeterminate+           #x0002)
(defconstant +bst-pushed+                  #x0004)
(defconstant +bst-focus+                   #x0008)

(defconstant +cbm-init+                      #x04)

(defconstant +cc-rgbinit+              #x00000001)
(defconstant +cc-fullopen+             #x00000002)
(defconstant +cc-preventfullopen+      #x00000004)
(defconstant +cc-showhelp+             #x00000008)
(defconstant +cc-enablehook+           #x00000010)
(defconstant +cc-enabletemplate+       #x00000020)
(defconstant +cc-enabletemplatehandle+ #x00000040)
(defconstant +cc-solidcolor+           #x00000080)
(defconstant +cc-anycolor+             #x00000100)

(defconstant +ccerr-choosecolorcodes+      #x5000)

(defconstant +cchdevicename+                   32)

(defconstant +cderr-dialogfailure+         #xFFFF)
(defconstant +cderr-generalcodes+          #x0000)
(defconstant +cderr-structsize+            #x0001)
(defconstant +cderr-initialization+        #x0002)
(defconstant +cderr-notemplate+            #x0003)
(defconstant +cderr-nohinstance+           #x0004)
(defconstant +cderr-loadstrfailure+        #x0005)
(defconstant +cderr-findresfailure+        #x0006)
(defconstant +cderr-loadresfailure+        #x0007)
(defconstant +cderr-lockresfailure+        #x0008)
(defconstant +cderr-memallocfailure+       #x0009)
(defconstant +cderr-memlockfailure+        #x000A)
(defconstant +cderr-nohook+                #x000B)
(defconstant +cderr-registermsgfail+       #x000C)

;;;
;;; clipboard-related constants
;;;
(defconstant +cf-text+                          1)
(defconstant +cf-bitmap+                        2)
(defconstant +cf-metafilepict+                  3)
(defconstant +cf-sylk+                          4)
(defconstant +cf-dif+                           5)
(defconstant +cf-tiff+                          6)
(defconstant +cf-oemtext+                       7)
(defconstant +cf-dib+                           8)
(defconstant +cf-palette+                       9)
(defconstant +cf-pendata+                      10)
(defconstant +cf-riff+                         11)
(defconstant +cf-wave+                         12)
(defconstant +cf-unicodetext+                  13)
(defconstant +cf-enhmetafile+                  14)
(defconstant +cf-hdrop+                        15)
(defconstant +cf-locale+                       16)
(defconstant +cf-dibv5+                        17)

;;;
;;; font-related constants
;;;
(defconstant +cf-screenfonts+          #x00000001)
(defconstant +cf-printerfonts+         #x00000002)
(defconstant +cf-both+                 #x00000003)
(defconstant +cf-showhelp+             #x00000004)
(defconstant +cf-enablehook+           #x00000008)
(defconstant +cf-enabletemplate+       #x00000010)
(defconstant +cf-enabletemplatehandle+ #x00000020)
(defconstant +cf-inittologfontstruct+  #x00000040)
(defconstant +cf-usestyle+             #x00000080)
(defconstant +cf-effects+              #x00000100)
(defconstant +cf-apply+                #x00000200)
(defconstant +cf-ansionly+             #x00000400)
(defconstant +cf-scriptsonly+          #x00000400)
(defconstant +cf-novectorfonts+        #x00000800)
(defconstant +cf-nooemfonts+           #x00000800)
(defconstant +cf-nosimulations+        #x00001000)
(defconstant +cf-limitsize+            #x00002000)
(defconstant +cf-fixedpitchonly+       #x00004000)
(defconstant +cf-wysiwyg+              #x00008000)
(defconstant +cf-forcefontexist+       #x00010000)
(defconstant +cf-scalableonly+         #x00020000)
(defconstant +cf-ttonly+               #x00040000)
(defconstant +cf-nofacesel+            #x00080000)
(defconstant +cf-nostylesel+           #x00100000)
(defconstant +cf-nosizesel+            #x00200000)
(defconstant +cf-selectscript+         #x00400000)
(defconstant +cf-noscriptsel+          #x00800000)
(defconstant +cf-novertfonts+          #x01000000)

(defconstant +cferr-choosefontcodes+       #x2000)
(defconstant +cferr-nofonts+               #x2001)
(defconstant +cferr-maxlessthanmin+        #x2002)

(defconstant +color-scrollbar+                  0)
(defconstant +color-background+                 1)
(defconstant +color-activecaption+              2)
(defconstant +color-inactivecaption+            3)
(defconstant +color-menu+                       4)
(defconstant +color-window+                     5)
(defconstant +color-windowframe+                6)
(defconstant +color-menutext+                   7)
(defconstant +color-windowtext+                 8)
(defconstant +color-captiontext+                9)
(defconstant +color-activeborder+              10)
(defconstant +color-inactiveborder+            11)
(defconstant +color-appworkspace+              12)
(defconstant +color-highlight+                 13)
(defconstant +color-highlighttext+             14)
(defconstant +color-btnface+                   15)
(defconstant +color-btnshadow+                 16)
(defconstant +color-graytext+                  17)
(defconstant +color-btntext+                   18)
(defconstant +color-inactivecaptiontext+       19)
(defconstant +color-btnhighlight+              20)
(defconstant +color-3ddkshadow+                21)
(defconstant +color-3dlight+                   22)
(defconstant +color-infotext+                  23)
(defconstant +color-infobk+                    24)
(defconstant +color-hotlight+                  26)
(defconstant +color-gradientactivecaption+     27)
(defconstant +color-gradientinactivecaption+   28)
(defconstant +color-menuhilight+               29)
(defconstant +color-menubar+                   30)
(defconstant +color-desktop+                    1)
(defconstant +color-3dface+                    15)
(defconstant +color-3dshadow+                  16)
(defconstant +color-3dhighlight+               20)
(defconstant +color-3dhilight+                 20)
(defconstant +color-btnhilight+                20)

(defconstant +cs-vredraw+                  #x0001)
(defconstant +cs-hredraw+                  #x0002)
(defconstant +cs-dblclks+                  #x0008)
(defconstant +cs-owndc+                    #x0020)
(defconstant +cs-classdc+                  #x0040)
(defconstant +cs-parentdc+                 #x0080)
(defconstant +cs-noclose+                  #x0200)
(defconstant +cs-savebits+                 #x0800)
(defconstant +cs-bytealignclient+          #x1000)
(defconstant +cs-bytealignwindow+          #x2000)
(defconstant +cs-globalclass+              #x4000)
(defconstant +cs-ime+                     #x10000)
(defconstant +cs-dropshadow+              #x20000)

(defconstant +cw-usedefault+           #x80000000)

(defconstant +dib-rgb-colors+                   0)
(defconstant +dib-pal-colors+                   1)

(defconstant +dm-getdefid+                 #x0400)
(defconstant +dm-setdefid+                 #x0401)
(defconstant +dm-reposition+               #x0402)

(defconstant +dt-top+                  #x00000000)
(defconstant +dt-left+                 #x00000000)
(defconstant +dt-center+               #x00000001)
(defconstant +dt-right+                #x00000002)
(defconstant +dt-vcenter+              #x00000004)
(defconstant +dt-bottom+               #x00000008)
(defconstant +dt-wordbreak+            #x00000010)
(defconstant +dt-singleline+           #x00000020)
(defconstant +dt-expandtabs+           #x00000040)
(defconstant +dt-tabstop+              #x00000080)
(defconstant +dt-noclip+               #x00000100)
(defconstant +dt-externalleading+      #x00000200)
(defconstant +dt-calcrect+             #x00000400)
(defconstant +dt-noprefix+             #x00000800)
(defconstant +dt-internal+             #x00001000)
(defconstant +dt-editcontrol+          #x00002000)
(defconstant +dt-path-ellipsis+        #x00004000)
(defconstant +dt-end-ellipsis+         #x00008000)
(defconstant +dt-modifystring+         #x00010000)
(defconstant +dt-rtlreading+           #x00020000)
(defconstant +dt-word-ellipsis+        #x00040000)
(defconstant +dt-nofullwidthcharbreak+ #x00080000)
(defconstant +dt-hideprefix+           #x00100000)
(defconstant +dt-prefixonly+           #x00200000)

(defconstant +em-getsel+                   #x00B0)
(defconstant +em-setsel+                   #x00B1)
(defconstant +em-getrect+                  #x00B2)
(defconstant +em-setrect+                  #x00B3)
(defconstant +em-setrectnp+                #x00B4)
(defconstant +em-scroll+                   #x00B5)
(defconstant +em-linescroll+               #x00B6)
(defconstant +em-scrollcaret+              #x00B7)
(defconstant +em-getmodify+                #x00B8)
(defconstant +em-setmodify+                #x00B9)
(defconstant +em-getlinecount+             #x00BA)
(defconstant +em-lineindex+                #x00BB)
(defconstant +em-sethandle+                #x00BC)
(defconstant +em-gethandle+                #x00BD)
(defconstant +em-getthumb+                 #x00BE)
(defconstant +em-linelength+               #x00C1)
(defconstant +em-replacesel+               #x00C2)
(defconstant +em-getline+                  #x00C4)
(defconstant +em-limittext+                #x00C5)
(defconstant +em-canundo+                  #x00C6)
(defconstant +em-undo+                     #x00C7)
(defconstant +em-fmtlines+                 #x00C8)
(defconstant +em-linefromchar+             #x00C9)
(defconstant +em-settabstops+              #x00CB)
(defconstant +em-setpasswordchar+          #x00CC)
(defconstant +em-emptyundobuffer+          #x00CD)
(defconstant +em-getfirstvisibleline+      #x00CE)
(defconstant +em-setreadonly+              #x00CF)
(defconstant +em-setwordbreakproc+         #x00D0)
(defconstant +em-getwordbreakproc+         #x00D1)
(defconstant +em-getpasswordchar+          #x00D2)
(defconstant +em-setmargins+               #x00D3)
(defconstant +em-getmargins+               #x00D4)
(defconstant +em-setlimittext+             #x00C5)
(defconstant +em-getlimittext+             #x00D5)
(defconstant +em-posfromchar+              #x00D6)
(defconstant +em-charfrompos+              #x00D7)
(defconstant +em-setimestatus+             #x00D8)
(defconstant +em-getimestatus+             #x00D9)

(defconstant +en-setfocus+                 #x0100)
(defconstant +en-killfocus+                #x0200)
(defconstant +en-change+                   #x0300)
(defconstant +en-update+                   #x0400)
(defconstant +en-errspace+                 #x0500)
(defconstant +en-maxtext+                  #x0501)
(defconstant +en-hscroll+                  #x0601)
(defconstant +en-vscroll+                  #x0602)
(defconstant +en-align-ltr-ec+             #x0700)
(defconstant +en-align-rtl-ec+             #x0701)

(defconstant +es-left+                     #x0000)
(defconstant +es-center+                   #x0001)
(defconstant +es-right+                    #x0002)
(defconstant +es-multiline+                #x0004)
(defconstant +es-uppercase+                #x0008)
(defconstant +es-lowercase+                #x0010)
(defconstant +es-password+                 #x0020)
(defconstant +es-autovscroll+              #x0040)
(defconstant +es-autohscroll+              #x0080)
(defconstant +es-nohidesel+                #x0100)
(defconstant +es-oemconvert+               #x0400)
(defconstant +es-readonly+                 #x0800)
(defconstant +es-wantreturn+               #x1000)
(defconstant +es-number+                   #x2000)

(defconstant +eto-opaque+                  #x0002)
(defconstant +eto-clipped+                 #x0004)
(defconstant +eto-glyph-index+             #x0010)
(defconstant +eto-rtlreading+              #x0080)
(defconstant +eto-numericslocal+           #x0400)
(defconstant +eto-numericslatin+           #x0800)
(defconstant +eto-ignorelanguage+          #x1000)
(defconstant +eto-pdy+                     #x2000)

(defconstant +fnerr-filenamecodes+         #x3000)
(defconstant +fnerr-subclassfailure+       #x3001)
(defconstant +fnerr-invalidfilename+       #x3002)
(defconstant +fnerr-buffertoosmall+        #x3003)

(defconstant +ff-dontcare+                 #x0000)
(defconstant +ff-roman+                    #x0010)
(defconstant +ff-swiss+                    #x0020)
(defconstant +ff-modern+                   #x0030)
(defconstant +ff-script+                   #x0040)
(defconstant +ff-decorative+               #x0050)

(defconstant +fr-private+                    #x10)
(defconstant +fr-not-enum+                   #x20)

;;;
;;; find/replace dialog-related constants
;;;
(defconstant +fr-down+                 #x00000001)
(defconstant +fr-wholeword+            #x00000002)
(defconstant +fr-matchcase+            #x00000004)
(defconstant +fr-findnext+             #x00000008)
(defconstant +fr-replace+              #x00000010)
(defconstant +fr-replaceall+           #x00000020)
(defconstant +fr-dialogterm+           #x00000040)
(defconstant +fr-showhelp+             #x00000080)
(defconstant +fr-enablehook+           #x00000100)
(defconstant +fr-enabletemplate+       #x00000200)
(defconstant +fr-noupdown+             #x00000400)
(defconstant +fr-nomatchcase+          #x00000800)
(defconstant +fr-nowholeword+          #x00001000)
(defconstant +fr-enabletemplatehandle+ #x00002000)
(defconstant +fr-hideupdown+           #x00004000)
(defconstant +fr-hidematchcase+        #x00008000)
(defconstant +fr-hidewholeword+        #x00010000)
(defconstant +fr-raw+                  #x00020000)
(defconstant +fr-matchdiac+            #x20000000)
(defconstant +fr-matchkashida+         #x40000000)
(defconstant +fr-matchalefhamza+       #x80000000)

(defconstant +frerr-findreplacecodes+      #x4000)
(defconstant +frerr-bufferlengthzero+      #x4001)

(defconstant +fw-dontcare+                      0)
(defconstant +fw-thin+                        100)
(defconstant +fw-extralight+                  200)
(defconstant +fw-light+                       300)
(defconstant +fw-normal+                      400)
(defconstant +fw-medium+                      500)
(defconstant +fw-semibold+                    600)
(defconstant +fw-bold+                        700)
(defconstant +fw-extrabold+                   800)
(defconstant +fw-heavy+                       900)

(defconstant +ga-parent+                        1)
(defconstant +ga-root+                          2)
(defconstant +ga-rootowner+                     3)

(defconstant +gclp-menuname+                   -8)
(defconstant +gclp-hbrbackground+             -10)
(defconstant +gclp-hcursor+                   -12)
(defconstant +gclp-hicon+                     -14)
(defconstant +gclp-hmodule+                   -16)
(defconstant +gcl-cbwndextra+                 -18)
(defconstant +gcl-cbclsextra+                 -20)
(defconstant +gclp-wndproc+                   -24)
(defconstant +gcl-style+                      -26)
(defconstant +gcw-atom+                       -32)
(defconstant +gclp-hiconsm+                   -34)

(defconstant +gm-compatible+                    1)
(defconstant +gm-advanced+                      2)
(defconstant +gm-last+                          3)

(defconstant +gwlp-wndproc+                    -4)
(defconstant +gwlp-hinstance+                  -6)
(defconstant +gwl-hwndparent+                  -8)
(defconstant +gwlp-id+                        -12)
(defconstant +gwl-style+                      -16)
(defconstant +gwl-exstyle+                    -20)
(defconstant +gwl-userdata+                   -21)

(defconstant +hs-horizontal+                    0)
(defconstant +hs-vertical+                      1)
(defconstant +hs-fdiagonal+                     2)
(defconstant +hs-bdiagonal+                     3)
(defconstant +hs-cross+                         4)
(defconstant +hs-diagcross+                     5)

(defconstant +hterror+                         -2)
(defconstant +httransparent+                   -1)
(defconstant +htnowhere+                        0)
(defconstant +htclient+                         1)
(defconstant +htcaption+                        2)
(defconstant +htsysmenu+                        3)
(defconstant +htgrowbox+                        4)
(defconstant +htsize+                           4)
(defconstant +htmenu+                           5)
(defconstant +hthscroll+                        6)
(defconstant +htvscroll+                        7)
(defconstant +htminbutton+                      8)
(defconstant +htmaxbutton+                      9)
(defconstant +htleft+                          10)
(defconstant +htright+                         11)
(defconstant +httop+                           12)
(defconstant +httopleft+                       13)
(defconstant +httopright+                      14)
(defconstant +htbottom+                        15)
(defconstant +htbottomleft+                    16)
(defconstant +htbottomright+                   17)
(defconstant +htborder+                        18)
(defconstant +htreduce+                         8)
(defconstant +htzoom+                           9)
(defconstant +htsizefirst+                     10)
(defconstant +htsizelast+                      17)
(defconstant +htobject+                        19)
(defconstant +htclose+                         20)
(defconstant +hthelp+                          21)

(defconstant +icc-listview-classes+    #x00000001)
(defconstant +icc-treeview-classes+    #x00000002)
(defconstant +icc-bar-classes+         #x00000004)
(defconstant +icc-tab-classes+         #x00000008)
(defconstant +icc-updown-class+        #x00000010)
(defconstant +icc-progress-class+      #x00000020)
(defconstant +icc-hotkey-class+        #x00000040)
(defconstant +icc-animate-class+       #x00000080)
(defconstant +icc-win95-classes+       #x000000FF)
(defconstant +icc-date-classes+        #x00000100)
(defconstant +icc-userex-classes+      #x00000200)
(defconstant +icc-cool-classes+        #x00000400)
(defconstant +icc-internet-classes+    #x00000800)
(defconstant +icc-pagescroller-class+  #x00001000)
(defconstant +icc-nativefntctl-class+  #x00002000)
(defconstant +icc-standard-classes+    #x00004000)
(defconstant +icc-link-class+          #x00008000)

(defconstant +icon-small+                       0)
(defconstant +icon-big+                         1)
(defconstant +icon-small2+                      2)

(defconstant +idok+                             1)
(defconstant +idcancel+                         2)
(defconstant +idabort+                          3)
(defconstant +idretry+                          4)
(defconstant +idignore+                         5)
(defconstant +idyes+                            6)
(defconstant +idno+                             7)
(defconstant +idclose+                          8)
(defconstant +idhelp+                           9)
(defconstant +idtryagain+                      10)
(defconstant +idcontinue+                      11)
(defconstant +idtimeout+                    32000)

(defconstant +image-bitmap+                     0)
(defconstant +image-icon+                       1)
(defconstant +image-cursor+                     2)
(defconstant +image-enhmetafile+                3)

(defconstant +lb-addstring+                #x0180)
(defconstant +lb-insertstring+             #x0181)
(defconstant +lb-deletestring+             #x0182)
(defconstant +lb-selitemrangeex+           #x0183)
(defconstant +lb-resetcontent+             #x0184)
(defconstant +lb-setsel+                   #x0185)
(defconstant +lb-setcursel+                #x0186)
(defconstant +lb-getsel+                   #x0187)
(defconstant +lb-getcursel+                #x0188)
(defconstant +lb-gettext+                  #x0189)
(defconstant +lb-gettextlen+               #x018A)
(defconstant +lb-getcount+                 #x018B)
(defconstant +lb-selectstring+             #x018C)
(defconstant +lb-dir+                      #x018D)
(defconstant +lb-gettopindex+              #x018E)
(defconstant +lb-findstring+               #x018F)
(defconstant +lb-getselcount+              #x0190)
(defconstant +lb-getselitems+              #x0191)
(defconstant +lb-settabstops+              #x0192)
(defconstant +lb-gethorizontalextent+      #x0193)
(defconstant +lb-sethorizontalextent+      #x0194)
(defconstant +lb-setcolumnwidth+           #x0195)
(defconstant +lb-addfile+                  #x0196)
(defconstant +lb-settopindex+              #x0197)
(defconstant +lb-getitemrect+              #x0198)
(defconstant +lb-getitemdata+              #x0199)
(defconstant +lb-setitemdata+              #x019A)
(defconstant +lb-selitemrange+             #x019B)
(defconstant +lb-setanchorindex+           #x019C)
(defconstant +lb-getanchorindex+           #x019D)
(defconstant +lb-setcaretindex+            #x019E)
(defconstant +lb-getcaretindex+            #x019F)
(defconstant +lb-setitemheight+            #x01A0)
(defconstant +lb-getitemheight+            #x01A1)
(defconstant +lb-findstringexact+          #x01A2)
(defconstant +lb-setlocale+                #x01A5)
(defconstant +lb-getlocale+                #x01A6)
(defconstant +lb-setcount+                 #x01A7)
(defconstant +lb-initstorage+              #x01A8)
(defconstant +lb-itemfrompoint+            #x01A9)
(defconstant +lb-multipleaddstring+        #x01B1)
(defconstant +lb-getlistboxinfo+           #x01B2)

(defconstant +lbn-errspace+                    -2)
(defconstant +lbn-selchange+                    1)
(defconstant +lbn-dblclk+                       2)
(defconstant +lbn-selcancel+                    3)
(defconstant +lbn-setfocus+                     4)
(defconstant +lbn-killfocus+                    5)

(defconstant +lbs-notify+                  #x0001)
(defconstant +lbs-sort+                    #x0002)
(defconstant +lbs-noredraw+                #x0004)
(defconstant +lbs-multiplesel+             #x0008)
(defconstant +lbs-ownerdrawfixed+          #x0010)
(defconstant +lbs-ownerdrawvariable+       #x0020)
(defconstant +lbs-hasstrings+              #x0040)
(defconstant +lbs-usetabstops+             #x0080)
(defconstant +lbs-nointegralheight+        #x0100)
(defconstant +lbs-multicolumn+             #x0200)
(defconstant +lbs-wantkeyboardinput+       #x0400)
(defconstant +lbs-extendedsel+             #x0800)
(defconstant +lbs-disablenoscroll+         #x1000)
(defconstant +lbs-nodata+                  #x2000)
(defconstant +lbs-nosel+                   #x4000)
(defconstant +lbs-combobox+                #x8000)

(defconstant +lf-facesize+                     32)
(defconstant +lf-fullfacesize+                 64)

(defconstant +lr-defaultcolor+             #x0000)
(defconstant +lr-monochrome+               #x0001)
(defconstant +lr-color+                    #x0002)
(defconstant +lr-copyreturnorg+            #x0004)
(defconstant +lr-copydeleteorg+            #x0008)
(defconstant +lr-loadfromfile+             #x0010)
(defconstant +lr-loadtransparent+          #x0020)
(defconstant +lr-defaultsize+              #x0040)
(defconstant +lr-vgacolor+                 #x0080)
(defconstant +lr-loadmap3dcolors+          #x1000)
(defconstant +lr-createdibsection+         #x2000)
(defconstant +lr-copyfromresource+         #x4000)
(defconstant +lr-shared+                   #x8000)

(defconstant +mb-ok+                   #x00000000)
(defconstant +mb-okcancel+             #x00000001)
(defconstant +mb-abortretryignore+     #x00000002)
(defconstant +mb-yesnocancel+          #x00000003)
(defconstant +mb-yesno+                #x00000004)
(defconstant +mb-retrycancel+          #x00000005)
(defconstant +mb-canceltrycontinue+    #x00000006)
(defconstant +mb-iconhand+             #x00000010)
(defconstant +mb-iconquestion+         #x00000020)
(defconstant +mb-iconexclamation+      #x00000030)
(defconstant +mb-iconasterisk+         #x00000040)
(defconstant +mb-usericon+             #x00000080)
(defconstant +mb-iconwarning+          #x00000030)
(defconstant +mb-iconerror+            #x00000010)
(defconstant +mb-iconinformation+      #x00000040)
(defconstant +mb-iconstop+             #x00000010)
(defconstant +mb-defbutton1+           #x00000000)
(defconstant +mb-defbutton2+           #x00000100)
(defconstant +mb-defbutton3+           #x00000200)
(defconstant +mb-defbutton4+           #x00000300)
(defconstant +mb-applmodal+            #x00000000)
(defconstant +mb-systemmodal+          #x00001000)
(defconstant +mb-taskmodal+            #x00002000)
(defconstant +mb-help+                 #x00004000)
(defconstant +mb-nofocus+              #x00008000)
(defconstant +mb-setforeground+        #x00010000)
(defconstant +mb-default-desktop-only+ #x00020000)
(defconstant +mb-topmost+              #x00040000)
(defconstant +mb-right+                #x00080000)
(defconstant +mb-rtlreading+           #x00100000)
(defconstant +mb-service-notification+ #x00200000)

(defconstant +mf-bycommand+            #x00000000)
(defconstant +mf-byposition+           #x00000400)

(defconstant +mfs-grayed+              #x00000003)
(defconstant +mfs-disabled+            #x00000003)
(defconstant +mfs-checked+             #x00000008)
(defconstant +mfs-hilite+              #x00000080)
(defconstant +mfs-enabled+             #x00000000)
(defconstant +mfs-unchecked+           #x00000000)
(defconstant +mfs-unhilite+            #x00000000)
(defconstant +mfs-default+             #x00001000)

(defconstant +mft-string+              #x00000000)
(defconstant +mft-bitmap+              #x00000004)
(defconstant +mft-menubarbreak+        #x00000020)
(defconstant +mft-menubreak+           #x00000040)
(defconstant +mft-ownerdraw+           #x00000100)
(defconstant +mft-radiocheck+          #x00000200)
(defconstant +mft-separator+           #x00000800)
(defconstant +mft-rightorder+          #x00002000)
(defconstant +mft-rightjustify+        #x00004000)

(defconstant +miim-state+              #x00000001)
(defconstant +miim-id+                 #x00000002)
(defconstant +miim-submenu+            #x00000004)
(defconstant +miim-checkmarks+         #x00000008)
(defconstant +miim-type+               #x00000010)
(defconstant +miim-data+               #x00000020)
(defconstant +miim-string+             #x00000040)
(defconstant +miim-bitmap+             #x00000080)
(defconstant +miim-ftype+              #x00000100)

(defconstant +mim-maxheight+           #x00000001)
(defconstant +mim-background+          #x00000002)
(defconstant +mim-helpid+              #x00000004)
(defconstant +mim-menudata+            #x00000008)
(defconstant +mim-style+               #x00000010)
(defconstant +mim-applytosubmenus+     #x80000000)

(defconstant +mk-lbutton+                  #x0001)
(defconstant +mk-rbutton+                  #x0002)
(defconstant +mk-shift+                    #x0004)
(defconstant +mk-control+                  #x0008)
(defconstant +mk-mbutton+                  #x0010)
(defconstant +mk-xbutton1+                 #x0020)
(defconstant +mk-xbutton2+                 #x0040)

(defconstant +mns-nocheck+             #x80000000)
(defconstant +mns-modeless+            #x40000000)
(defconstant +mns-dragdrop+            #x20000000)
(defconstant +mns-autodismiss+         #x10000000)
(defconstant +mns-notifybypos+         #x08000000)
(defconstant +mns-checkorbmp+          #x04000000)

(defconstant +monitor-defaulttonull+    #x00000000)
(defconstant +monitor-defaulttoprimary+ #x00000001)
(defconstant +monitor-defaulttonearest+ #x00000002)

(defconstant +monitorinfoof-primary+   #x00000001)

(defconstant +obm-lfarrowi+                 32734)
(defconstant +obm-rgarrowi+                 32735)
(defconstant +obm-dnarrowi+                 32736)
(defconstant +obm-uparrowi+                 32737)
(defconstant +obm-combo+                    32738)
(defconstant +obm-mnarrow+                  32739)
(defconstant +obm-lfarrowd+                 32740)
(defconstant +obm-rgarrowd+                 32741)
(defconstant +obm-dnarrowd+                 32742)
(defconstant +obm-uparrowd+                 32743)
(defconstant +obm-restored+                 32744)
(defconstant +obm-zoomd+                    32745)
(defconstant +obm-reduced+                  32746)
(defconstant +obm-restore+                  32747)
(defconstant +obm-zoom+                     32748)
(defconstant +obm-reduce+                   32749)
(defconstant +obm-lfarrow+                  32750)
(defconstant +obm-rgarrow+                  32751)
(defconstant +obm-dnarrow+                  32752)
(defconstant +obm-uparrow+                  32753)
(defconstant +obm-close+                    32754)
(defconstant +obm-old-restore+              32755)
(defconstant +obm-old-zoom+                 32756)
(defconstant +obm-old-reduce+               32757)
(defconstant +obm-btncorners+               32758)
(defconstant +obm-checkboxes+               32759)
(defconstant +obm-check+                    32760)
(defconstant +obm-btsize+                   32761)
(defconstant +obm-old-lfarrow+              32762)
(defconstant +obm-old-rgarrow+              32763)
(defconstant +obm-old-dnarrow+              32764)
(defconstant +obm-old-uparrow+              32765)
(defconstant +obm-size+                     32766)
(defconstant +obm-old-close+                32767)

(defconstant +obj-pen+                          1)
(defconstant +obj-brush+                        2)
(defconstant +obj-dc+                           3)
(defconstant +obj-metadc+                       4)
(defconstant +obj-pal+                          5)
(defconstant +obj-font+                         6)
(defconstant +obj-bitmap+                       7)
(defconstant +obj-region+                       8)
(defconstant +obj-metafile+                     9)
(defconstant +obj-memdc+                       10)
(defconstant +obj-extpen+                      11)
(defconstant +obj-enhmetadc+                   12)
(defconstant +obj-enhmetafile+                 13)
(defconstant +obj-colorspace+                  14)

(defconstant +ofn-readonly+            #x00000001)
(defconstant +ofn-overwriteprompt+     #x00000002)
(defconstant +ofn-hidereadonly+        #x00000004)
(defconstant +ofn-nochangedir+         #x00000008)
(defconstant +ofn-showhelp+            #x00000010)
(defconstant +ofn-enablehook+          #x00000020)
(defconstant +ofn-enabletemplate+      #x00000040)
(defconstant +ofn-enabletemplatehandle+ #x00000080)
(defconstant +ofn-novalidate+          #x00000100)
(defconstant +ofn-allowmultiselect+    #x00000200)
(defconstant +ofn-extensiondifferent+  #x00000400)
(defconstant +ofn-pathmustexist+       #x00000800)
(defconstant +ofn-filemustexist+       #x00001000)
(defconstant +ofn-createprompt+        #x00002000)
(defconstant +ofn-shareaware+          #x00004000)
(defconstant +ofn-noreadonlyreturn+    #x00008000)
(defconstant +ofn-notestfilecreate+    #x00010000)
(defconstant +ofn-nonetworkbutton+     #x00020000)
(defconstant +ofn-nolongnames+         #x00040000)
(defconstant +ofn-explorer+            #x00080000)
(defconstant +ofn-nodereferencelinks+  #x00100000)
(defconstant +ofn-longnames+           #x00200000)
(defconstant +ofn-enableincludenotify+ #x00400000)
(defconstant +ofn-enablesizing+        #x00800000)
(defconstant +ofn-dontaddtorecent+     #x02000000)
(defconstant +ofn-forceshowhidden+     #x10000000)
(defconstant +ofn-ex-noplacesbar+      #x00000001)

(defconstant +ofn-sharefallthrough             2)
(defconstant +ofn-sharenowarn                  1)
(defconstant +ofn-sharewarn                    0)

(defconstant +oic-sample+                   32512)
(defconstant +oic-hand+                     32513)
(defconstant +oic-ques+                     32514)
(defconstant +oic-bang+                     32515)
(defconstant +oic-note+                     32516)
(defconstant +oic-winlogo+                  32517)
(defconstant +oic-warning+                  32515)
(defconstant +oic-error+                    32513)
(defconstant +oic-information+              32516)

(defconstant +ocr-normal+                   32512)
(defconstant +ocr-ibeam+                    32513)
(defconstant +ocr-wait+                     32514)
(defconstant +ocr-cross+                    32515)
(defconstant +ocr-up+                       32516)
(defconstant +ocr-sizenwse+                 32642)
(defconstant +ocr-sizenesw+                 32643)
(defconstant +ocr-sizewe+                   32644)
(defconstant +ocr-sizens+                   32645)
(defconstant +ocr-sizeall+                  32646)
(defconstant +ocr-no+                       32648)
(defconstant +ocr-hand+                     32649)
(defconstant +ocr-appstarting+              32650)

(defconstant +out-default-precis+               0)
(defconstant +out-string-precis+                1)
(defconstant +out-character-precis+             2)
(defconstant +out-stroke-precis+                3)
(defconstant +out-tt-precis+                    4)
(defconstant +out-device-precis+                5)
(defconstant +out-raster-precis+                6)
(defconstant +out-tt-only-precis+               7)
(defconstant +out-outline-precis+               8)
(defconstant +out-screen-outline-precis+        9)
(defconstant +out-ps-only-precis+              10)

;;;
;;; progress bar messages and style bits
;;;

(defconstant +pbm-setrange+                #x0401) ; (WM_USER+1)
(defconstant +pbm-setpos+                  #x0402) ; (WM_USER+2)
(defconstant +pbm-deltapos+                #x0403) ; (WM_USER+3)
(defconstant +pbm-setstep+                 #x0404) ; (WM_USER+4)
(defconstant +pbm-stepit+                  #x0405) ; (WM_USER+5)
(defconstant +pbm-setrange32+              #x0406) ; (WM_USER+6)
(defconstant +pbm-getrange+                #x0407) ; (WM_USER+7)
(defconstant +pbm-getpos+                  #x0408) ; (WM_USER+8)
(defconstant +pbm-setbarcolor+             #x0409) ; (WM_USER+9)
(defconstant +pbm-setbkcolor+              #x2001) ; CCM_SETBKCOLOR
(defconstant +pbm-setmarquee+              #x040a) ; (WM_USER+10)
(defconstant +pbm-getstep+                 #x040d) ; (WM_USER+13)
(defconstant +pbm-getbkcolor+              #x040e) ; (WM_USER+14)
(defconstant +pbm-getbarcolor+             #x040f) ; (WM_USER+15)
(defconstant +pbm-setstate+                #x0410) ; (WM_USER+16)
(defconstant +pbm-getstate+                #x0411) ; (WM_USER+17)

(defconstant +pbs-smooth+                    #x01)
(defconstant +pbs-vertical+                  #x04)
(defconstant +pbs-marquee+                   #x08)
(defconstant +pbs-smoothreverse+             #x10)

(defconstant +pbst-normal+                 #x0001)
(defconstant +pbst-error+                  #x0002)
(defconstant +pbst-paused+                 #x0003)

(defconstant +pderr-printercodes+          #x1000)
(defconstant +pderr-setupfailure+          #x1001)
(defconstant +pderr-parsefailure+          #x1002)
(defconstant +pderr-retdeffailure+         #x1003)
(defconstant +pderr-loaddrvfailure+        #x1004)
(defconstant +pderr-getdevmodefail+        #x1005)
(defconstant +pderr-initfailure+           #x1006)
(defconstant +pderr-nodevices+             #x1007)
(defconstant +pderr-nodefaultprn+          #x1008)
(defconstant +pderr-dndmmismatch+          #x1009)
(defconstant +pderr-createicfailure+       #x100a)
(defconstant +pderr-printernotfound+       #x100B)
(defconstant +pderr-defaultdifferent+      #x100C)

(defconstant +qs-key+                      #x0001)
(defconstant +qs-mousemove+                #x0002)
(defconstant +qs-mousebutton+              #x0004)
(defconstant +qs-postmessage+              #x0008)
(defconstant +qs-timer+                    #x0010)
(defconstant +qs-paint+                    #x0020)
(defconstant +qs-sendmessage+              #x0040)
(defconstant +qs-hotkey+                   #x0080)
(defconstant +qs-allpostmessage+           #x0100)
(defconstant +qs-rawinput+                 #x0400)
(defconstant +qs-mouse+                    (logior +qs-mousemove+
                                                   +qs-mousebutton+))
(defconstant +qs-input+                    (logior +qs-mouse+
                                                   +qs-key+
                                                   +qs-rawinput+))
(defconstant +qs-allevents+                (logior +qs-input+
                                                   +qs-postmessage+
                                                   +qs-timer+
                                                   +qs-paint+
                                                   +qs-hotkey+))
(defconstant +qs-allinput+                 (logior +qs-input+
                                                   +qs-postmessage+
                                                   +qs-timer+
                                                   +qs-paint+
                                                   +qs-hotkey+
                                                   +qs-sendmessage+))

(defconstant +pm-noremove+                 #x0000)
(defconstant +pm-remove+                   #x0001)
(defconstant +pm-noyield+                  #x0002)
(defconstant +pm-qs-input+                 (ash +qs-input+ 16))
(defconstant +pm-qs-postmessage+           (ash (logior +qs-postmessage+
                                                        +qs-hotkey+
                                                        +qs-timer+)
                                                16))
(defconstant +pm-qs-paint+                 (ash +qs-paint+ 16))
(defconstant +pm-qs-sendmessage+           (ash +qs-sendmessage+ 16))

(defconstant +ps-solid+                         0)
(defconstant +ps-dash+                          1)
(defconstant +ps-dot+                           2)
(defconstant +ps-dashdot+                       3)
(defconstant +ps-dashdotdot+                    4)
(defconstant +ps-null+                          5)
(defconstant +ps-insideframe+                   6)
(defconstant +ps-userstyle+                     7)
(defconstant +ps-alternate+                     8)
(defconstant +ps-style-mask+           #x0000000F)
(defconstant +ps-endcap-round+         #x00000000)
(defconstant +ps-endcap-square+        #x00000100)
(defconstant +ps-endcap-flat+          #x00000200)
(defconstant +ps-endcap-mask+          #x00000F00)
(defconstant +ps-join-round+           #x00000000)
(defconstant +ps-join-bevel+           #x00001000)
(defconstant +ps-join-miter+           #x00002000)
(defconstant +ps-join-mask+            #x0000F000)
(defconstant +ps-cosmetic+             #x00000000)
(defconstant +ps-geometric+            #x00010000)
(defconstant +ps-type-mask+            #x000F0000)

;;;
;;; scrollbar constants
;;;

(defconstant +sb-horz+                          0)
(defconstant +sb-vert+                          1)
(defconstant +sb-ctl+                           2)
(defconstant +sb-both+                          3)

(defconstant +sb-lineup+                        0)
(defconstant +sb-lineleft+                      0)
(defconstant +sb-linedown+                      1)
(defconstant +sb-lineright+                     1)
(defconstant +sb-pageup+                        2)
(defconstant +sb-pageleft+                      2)
(defconstant +sb-pagedown+                      3)
(defconstant +sb-pageright+                     3)
(defconstant +sb-thumbposition+                 4)
(defconstant +sb-thumbtrack+                    5)
(defconstant +sb-top+                           6)
(defconstant +sb-left+                          6)
(defconstant +sb-bottom+                        7)
(defconstant +sb-right+                         7)
(defconstant +sb-endscroll+                     8)

;;;
;;; statusbar constants
;;;

(defconstant +sb-simpleid+                 #x00FF)

(defconstant +sb-settext+                  #x0401) ; (WM_USER+1) SB_SETTEXTA
(defconstant +sb-gettext+                  #x0402) ; (WM_USER+2) SB_GETTEXTA
(defconstant +sb-gettextlength+            #x0403) ; (WM_USER+3) SB_GETTEXTLENGTHA
(defconstant +sb-setparts+                 #x0404) ; (WM_USER+4)
(defconstant +sb-getparts+                 #x0406) ; (WM_USER+6)
(defconstant +sb-getborders+               #x0407) ; (WM_USER+7)
(defconstant +sb-setminheight+             #x0408) ; (WM_USER+8)
(defconstant +sb-simple+                   #x0409) ; (WM_USER+9)
(defconstant +sb-getrect+                  #x040A) ; (WM_USER+10)
(defconstant +sb-issimple+                 #x040E) ; (WM_USER+14)
(defconstant +sb-seticon+                  #x040F) ; (WM_USER+15)
(defconstant +sb-settiptexta+              #x0410) ; (WM_USER+16)
(defconstant +sb-settiptextw+              #x0411) ; (WM_USER+17)
(defconstant +sb-gettiptexta+              #x0412) ; (WM_USER+18)
(defconstant +sb-gettiptextw+              #x0413) ; (WM_USER+19)
(defconstant +sb-geticon+                  #x0414) ; (WM_USER+20)
(defconstant +sb-setunicodeformat+         #x2005) ; CCM_SETUNICODEFORMAT
(defconstant +sb-getunicodeformat+         #x2006) ; CCM_GETUNICODEFORMAT

(defconstant +sbars-sizegrip+              #x0100)
(defconstant +sbars-tooltips+              #x0800)

(defconstant +sbs-horz+                    #x0000)
(defconstant +sbs-vert+                    #x0001)
(defconstant +sbs-topalign+                #x0002)
(defconstant +sbs-leftalign+               #x0002)
(defconstant +sbs-bottomalign+             #x0004)
(defconstant +sbs-rightalign+              #x0004)
(defconstant +sbs-sizeboxtopleftalign+     #x0002)
(defconstant +sbs-sizeboxbottomrightalign+ #x0004)
(defconstant +sbs-sizebox+                 #x0008)
(defconstant +sbs-sizegrip+                #x0010)

(defconstant +sbt-ownerdraw+               #x1000)
(defconstant +sbt-noborders+               #x0100)
(defconstant +sbt-popout+                  #x0200)
(defconstant +sbt-rtlreading+              #x0400)
(defconstant +sbt-notabparsing+            #x0800)

(defconstant +sif-range+                   #x0001)
(defconstant +sif-page+                    #x0002)
(defconstant +sif-pos+                     #x0004)
(defconstant +sif-disablenoscroll+         #x0008)
(defconstant +sif-trackpos+                #x0010)
(defconstant +sif-all+                     #x0017)

(defconstant +size-restored+                    0)
(defconstant +size-minimized+                   1)
(defconstant +size-maximized+                   2)
(defconstant +size-maxshow+                     3)
(defconstant +size-maxhide+                     4)

(defconstant +sm-cxscreen+                      0)
(defconstant +sm-cyscreen+                      1)
(defconstant +sm-cxvscroll+                     2)
(defconstant +sm-cyhscroll+                     3)
(defconstant +sm-cycaption+                     4)
(defconstant +sm-cxborder+                      5)
(defconstant +sm-cyborder+                      6)
(defconstant +sm-cxdlgframe+                    7)
(defconstant +sm-cydlgframe+                    8)
(defconstant +sm-cyvthumb+                      9)
(defconstant +sm-cxhthumb+                     10)
(defconstant +sm-cxicon+                       11)
(defconstant +sm-cyicon+                       12)
(defconstant +sm-cxcursor+                     13)
(defconstant +sm-cycursor+                     14)
(defconstant +sm-cymenu+                       15)
(defconstant +sm-cxfullscreen+                 16)
(defconstant +sm-cyfullscreen+                 17)
(defconstant +sm-cykanjiwindow+                18)
(defconstant +sm-mousepresent+                 19)
(defconstant +sm-cyvscroll+                    20)
(defconstant +sm-cxhscroll+                    21)
(defconstant +sm-debug+                        22)
(defconstant +sm-swapbutton+                   23)
(defconstant +sm-reserved1+                    24)
(defconstant +sm-reserved2+                    25)
(defconstant +sm-reserved3+                    26)
(defconstant +sm-reserved4+                    27)
(defconstant +sm-cxmin+                        28)
(defconstant +sm-cymin+                        29)
(defconstant +sm-cxsize+                       30)
(defconstant +sm-cysize+                       31)
(defconstant +sm-cxframe+                      32)
(defconstant +sm-cyframe+                      33)
(defconstant +sm-cxmintrack+                   34)
(defconstant +sm-cymintrack+                   35)
(defconstant +sm-cxdoubleclk+                  36)
(defconstant +sm-cydoubleclk+                  37)
(defconstant +sm-cxiconspacing+                38)
(defconstant +sm-cyiconspacing+                39)
(defconstant +sm-menudropalignment+            40)
(defconstant +sm-penwindows+                   41)
(defconstant +sm-dbcsenabled+                  42)
(defconstant +sm-cmousebuttons+                43)
(defconstant +sm-cxfixedframe+    +sm-cxdlgframe+)
(defconstant +sm-cyfixedframe+    +sm-cydlgframe+)
(defconstant +sm-cxsizeframe+        +sm-cxframe+)
(defconstant +sm-cysizeframe+        +sm-cyframe+)
(defconstant +sm-secure+                       44)
(defconstant +sm-cxedge+                       45)
(defconstant +sm-cyedge+                       46)
(defconstant +sm-cxminspacing+                 47)
(defconstant +sm-cyminspacing+                 48)
(defconstant +sm-cxsmicon+                     49)
(defconstant +sm-cysmicon+                     50)
(defconstant +sm-cysmcaption+                  51)
(defconstant +sm-cxsmsize+                     52)
(defconstant +sm-cysmsize+                     53)
(defconstant +sm-cxmenusize+                   54)
(defconstant +sm-cymenusize+                   55)
(defconstant +sm-arrange+                      56)
(defconstant +sm-cxminimized+                  57)
(defconstant +sm-cyminimized+                  58)
(defconstant +sm-cxmaxtrack+                   59)
(defconstant +sm-cymaxtrack+                   60)
(defconstant +sm-cxmaximized+                  61)
(defconstant +sm-cymaximized+                  62)
(defconstant +sm-network+                      63)
(defconstant +sm-cleanboot+                    67)
(defconstant +sm-cxdrag+                       68)
(defconstant +sm-cydrag+                       69)
(defconstant +sm-showsounds+                   70)
(defconstant +sm-cxmenucheck+                  71)
(defconstant +sm-cymenucheck+                  72)
(defconstant +sm-slowmachine+                  73)
(defconstant +sm-mideastenabled+               74)
(defconstant +sm-mousewheelpresent+            75)
(defconstant +sm-xvirtualscreen+               76)
(defconstant +sm-yvirtualscreen+               77)
(defconstant +sm-cxvirtualscreen+              78)
(defconstant +sm-cyvirtualscreen+              79)
(defconstant +sm-cmonitors+                    80)
(defconstant +sm-samedisplayformat+            81)
(defconstant +sm-immenabled+                   82)
(defconstant +sm-cxfocusborder+                83)
(defconstant +sm-cyfocusborder+                84)
(defconstant +sm-tabletpc+                     86)
(defconstant +sm-mediacenter+                  87)
(defconstant +sm-starter+                      88)
(defconstant +sm-serverr2+                     89)
(defconstant +sm-remotesession+            #x1000)
(defconstant +sm-shuttingdown+             #x2000)
(defconstant +sm-remotecontrol+            #x2001)
(defconstant +sm-caretblinkingenabled+     #x2002)

(defconstant +spi-getbeep+                 #x0001)
(defconstant +spi-setbeep+                 #x0002)
(defconstant +spi-getmouse+                #x0003)
(defconstant +spi-setmouse+                #x0004)
(defconstant +spi-getborder+               #x0005)
(defconstant +spi-setborder+               #x0006)
(defconstant +spi-getkeyboardspeed+        #x000A)
(defconstant +spi-setkeyboardspeed+        #x000B)
(defconstant +spi-langdriver+              #x000C)
(defconstant +spi-iconhorizontalspacing+   #x000D)
(defconstant +spi-getscreensavetimeout+    #x000E)
(defconstant +spi-setscreensavetimeout+    #x000F)
(defconstant +spi-getscreensaveactive+     #x0010)
(defconstant +spi-setscreensaveactive+     #x0011)
(defconstant +spi-getgridgranularity+      #x0012)
(defconstant +spi-setgridgranularity+      #x0013)
(defconstant +spi-setdeskwallpaper+        #x0014)
(defconstant +spi-setdeskpattern+          #x0015)
(defconstant +spi-getkeyboarddelay+        #x0016)
(defconstant +spi-setkeyboarddelay+        #x0017)
(defconstant +spi-iconverticalspacing+     #x0018)
(defconstant +spi-geticontitlewrap+        #x0019)
(defconstant +spi-seticontitlewrap+        #x001A)
(defconstant +spi-getmenudropalignment+    #x001B)
(defconstant +spi-setmenudropalignment+    #x001C)
(defconstant +spi-setdoubleclkwidth+       #x001D)
(defconstant +spi-setdoubleclkheight+      #x001E)
(defconstant +spi-geticontitlelogfont+     #x001F)
(defconstant +spi-setdoubleclicktime+      #x0020)
(defconstant +spi-setmousebuttonswap+      #x0021)
(defconstant +spi-seticontitlelogfont+     #x0022)
(defconstant +spi-getfasttaskswitch+       #x0023)
(defconstant +spi-setfasttaskswitch+       #x0024)
(defconstant +spi-setdragfullwindows+      #x0025)
(defconstant +spi-getdragfullwindows+      #x0026)
(defconstant +spi-getnonclientmetrics+     #x0029)
(defconstant +spi-setnonclientmetrics+     #x002A)
(defconstant +spi-getminimizedmetrics+     #x002B)
(defconstant +spi-setminimizedmetrics+     #x002C)
(defconstant +spi-geticonmetrics+          #x002D)
(defconstant +spi-seticonmetrics+          #x002E)
(defconstant +spi-setworkarea+             #x002F)
(defconstant +spi-getworkarea+             #x0030)
(defconstant +spi-setpenwindows+           #x0031)
(defconstant +spi-gethighcontrast+         #x0042)
(defconstant +spi-sethighcontrast+         #x0043)
(defconstant +spi-getkeyboardpref+         #x0044)
(defconstant +spi-setkeyboardpref+         #x0045)
(defconstant +spi-getscreenreader+         #x0046)
(defconstant +spi-setscreenreader+         #x0047)
(defconstant +spi-getanimation+            #x0048)
(defconstant +spi-setanimation+            #x0049)
(defconstant +spi-getfontsmoothing+        #x004A)
(defconstant +spi-setfontsmoothing+        #x004B)
(defconstant +spi-setdragwidth+            #x004C)
(defconstant +spi-setdragheight+           #x004D)
(defconstant +spi-sethandheld+             #x004E)
(defconstant +spi-getlowpowertimeout+      #x004F)
(defconstant +spi-getpowerofftimeout+      #x0050)
(defconstant +spi-setlowpowertimeout+      #x0051)
(defconstant +spi-setpowerofftimeout+      #x0052)
(defconstant +spi-getlowpoweractive+       #x0053)
(defconstant +spi-getpoweroffactive+       #x0054)
(defconstant +spi-setlowpoweractive+       #x0055)
(defconstant +spi-setpoweroffactive+       #x0056)
(defconstant +spi-setcursors+              #x0057)
(defconstant +spi-seticons+                #x0058)
(defconstant +spi-getdefaultinputlang+     #x0059)
(defconstant +spi-setdefaultinputlang+     #x005A)
(defconstant +spi-setlangtoggle+           #x005B)
(defconstant +spi-getwindowsextension+     #x005C)
(defconstant +spi-setmousetrails+          #x005D)
(defconstant +spi-getmousetrails+          #x005E)
(defconstant +spi-setscreensaverrunning+   #x0061)
(defconstant +spi-screensaverrunning+      #x0061)
(defconstant +spi-getfilterkeys+           #x0032)
(defconstant +spi-setfilterkeys+           #x0033)
(defconstant +spi-gettogglekeys+           #x0034)
(defconstant +spi-settogglekeys+           #x0035)
(defconstant +spi-getmousekeys+            #x0036)
(defconstant +spi-setmousekeys+            #x0037)
(defconstant +spi-getshowsounds+           #x0038)
(defconstant +spi-setshowsounds+           #x0039)
(defconstant +spi-getstickykeys+           #x003A)
(defconstant +spi-setstickykeys+           #x003B)
(defconstant +spi-getaccesstimeout+        #x003C)
(defconstant +spi-setaccesstimeout+        #x003D)
(defconstant +spi-getserialkeys+           #x003E)
(defconstant +spi-setserialkeys+           #x003F)
(defconstant +spi-getsoundsentry+          #x0040)
(defconstant +spi-setsoundsentry+          #x0041)
(defconstant +spi-getsnaptodefbutton+      #x005F)
(defconstant +spi-setsnaptodefbutton+      #x0060)
(defconstant +spi-getmousehoverwidth+      #x0062)
(defconstant +spi-setmousehoverwidth+      #x0063)
(defconstant +spi-getmousehoverheight+     #x0064)
(defconstant +spi-setmousehoverheight+     #x0065)
(defconstant +spi-getmousehovertime+       #x0066)
(defconstant +spi-setmousehovertime+       #x0067)
(defconstant +spi-getwheelscrolllines+     #x0068)
(defconstant +spi-setwheelscrolllines+     #x0069)
(defconstant +spi-getmenushowdelay+        #x006A)
(defconstant +spi-setmenushowdelay+        #x006B)
(defconstant +spi-getshowimeui+            #x006E)
(defconstant +spi-setshowimeui+            #x006F)
(defconstant +spi-getmousespeed+           #x0070)
(defconstant +spi-setmousespeed+           #x0071)
(defconstant +spi-getscreensaverrunning+   #x0072)
(defconstant +spi-getdeskwallpaper+        #x0073)
(defconstant +spi-getactivewindowtracking+ #x1000)
(defconstant +spi-setactivewindowtracking+ #x1001)
(defconstant +spi-getmenuanimation+        #x1002)
(defconstant +spi-setmenuanimation+        #x1003)
(defconstant +spi-getcomboboxanimation+    #x1004)
(defconstant +spi-setcomboboxanimation+    #x1005)
(defconstant +spi-getlistboxsmoothscrolling+ #x1006)
(defconstant +spi-setlistboxsmoothscrolling+ #x1007)
(defconstant +spi-getgradientcaptions+     #x1008)
(defconstant +spi-setgradientcaptions+     #x1009)
(defconstant +spi-getkeyboardcues+         #x100A)
(defconstant +spi-setkeyboardcues+         #x100B)
(defconstant +spi-getmenuunderlines+       #x100A)
(defconstant +spi-setmenuunderlines+       #x100B)
(defconstant +spi-getactivewndtrkzorder+   #x100C)
(defconstant +spi-setactivewndtrkzorder+   #x100D)
(defconstant +spi-gethottracking+          #x100E)
(defconstant +spi-sethottracking+          #x100F)
(defconstant +spi-getmenufade+             #x1012)
(defconstant +spi-setmenufade+             #x1013)
(defconstant +spi-getselectionfade+        #x1014)
(defconstant +spi-setselectionfade+        #x1015)
(defconstant +spi-gettooltipanimation+     #x1016)
(defconstant +spi-settooltipanimation+     #x1017)
(defconstant +spi-gettooltipfade+          #x1018)
(defconstant +spi-settooltipfade+          #x1019)
(defconstant +spi-getcursorshadow+         #x101A)
(defconstant +spi-setcursorshadow+         #x101B)
(defconstant +spi-getmousesonar+           #x101C)
(defconstant +spi-setmousesonar+           #x101D)
(defconstant +spi-getmouseclicklock+       #x101E)
(defconstant +spi-setmouseclicklock+       #x101F)
(defconstant +spi-getmousevanish+          #x1020)
(defconstant +spi-setmousevanish+          #x1021)
(defconstant +spi-getflatmenu+             #x1022)
(defconstant +spi-setflatmenu+             #x1023)
(defconstant +spi-getdropshadow+           #x1024)
(defconstant +spi-setdropshadow+           #x1025)
(defconstant +spi-getblocksendinputresets+ #x1026)
(defconstant +spi-setblocksendinputresets+ #x1027)
(defconstant +spi-getuieffects+            #x103E)
(defconstant +spi-setuieffects+            #x103F)
(defconstant +spi-getforegroundlocktimeout+ #x2000)
(defconstant +spi-setforegroundlocktimeout+ #x2001)
(defconstant +spi-getactivewndtrktimeout+  #x2002)
(defconstant +spi-setactivewndtrktimeout+  #x2003)
(defconstant +spi-getforegroundflashcount+ #x2004)
(defconstant +spi-setforegroundflashcount+ #x2005)
(defconstant +spi-getcaretwidth+           #x2006)
(defconstant +spi-setcaretwidth+           #x2007)
(defconstant +spi-getmouseclicklocktime+   #x2008)
(defconstant +spi-setmouseclicklocktime+   #x2009)
(defconstant +spi-getfontsmoothingtype+    #x200A)
(defconstant +spi-setfontsmoothingtype+    #x200B)
(defconstant +spi-getfontsmoothingcontrast+ #x200C)
(defconstant +spi-setfontsmoothingcontrast+ #x200D)
(defconstant +spi-getfocusborderwidth+     #x200E)
(defconstant +spi-setfocusborderwidth+     #x200F)
(defconstant +spi-getfocusborderheight+    #x2010)
(defconstant +spi-setfocusborderheight+    #x2011)
(defconstant +spi-getfontsmoothingorientation+ #x2012)
(defconstant +spi-setfontsmoothingorientation+ #x2013)

(defconstant +ss-left+                 #x00000000)
(defconstant +ss-center+               #x00000001)
(defconstant +ss-right+                #x00000002)
(defconstant +ss-icon+                 #x00000003)
(defconstant +ss-blackrect+            #x00000004)
(defconstant +ss-grayrect+             #x00000005)
(defconstant +ss-whiterect+            #x00000006)
(defconstant +ss-blackframe+           #x00000007)
(defconstant +ss-grayframe+            #x00000008)
(defconstant +ss-whiteframe+           #x00000009)
(defconstant +ss-useritem+             #x0000000A)
(defconstant +ss-simple+               #x0000000B)
(defconstant +ss-leftnowordwrap+       #x0000000C)
(defconstant +ss-ownerdraw+            #x0000000D)
(defconstant +ss-bitmap+               #x0000000E)
(defconstant +ss-enhmetafile+          #x0000000F)
(defconstant +ss-etchedhorz+           #x00000010)
(defconstant +ss-etchedvert+           #x00000011)
(defconstant +ss-etchedframe+          #x00000012)
(defconstant +ss-typemask+             #x0000001F)
(defconstant +ss-realsizecontrol+      #x00000040)
(defconstant +ss-noprefix+             #x00000080)
(defconstant +ss-notify+               #x00000100)
(defconstant +ss-centerimage+          #x00000200)
(defconstant +ss-rightjust+            #x00000400)
(defconstant +ss-realsizeimage+        #x00000800)
(defconstant +ss-sunken+               #x00001000)
(defconstant +ss-editcontrol+          #x00002000)
(defconstant +ss-endellipsis+          #x00004000)
(defconstant +ss-pathellipsis+         #x00008000)
(defconstant +ss-wordellipsis+         #x0000C000)
(defconstant +ss-ellipsismask+         #x0000C000)

(defconstant +stm-seticon+                 #x0170)
(defconstant +stm-geticon+                 #x0171)
(defconstant +stm-setimage+                #x0172)
(defconstant +stm-getimage+                #x0173)
(defconstant +stm-msgmax+                  #x0174)

(defconstant +stn-clicked+                      0)
(defconstant +stn-dblclk+                       1)
(defconstant +stn-enable+                       2)
(defconstant +stn-disable+                      3)

;;;
;;; commands for ScrollWindowEx()
;;;
(defconstant +sw-scrollchildren+           #x0001)
(defconstant +sw-invalidate+               #x0002)
(defconstant +sw-erase+                    #x0004)
(defconstant +sw-smoothscroll+             #x0010)

;;;
;;; commands for ShowWindow()
;;;
(defconstant +sw-hide+                          0)
(defconstant +sw-shownormal+                    1)
(defconstant +sw-normal+                        1)
(defconstant +sw-showminimized+                 2)
(defconstant +sw-showmaximized+                 3)
(defconstant +sw-maximize+                      3)
(defconstant +sw-shownoactivate+                4)
(defconstant +sw-show+                          5)
(defconstant +sw-minimize+                      6)
(defconstant +sw-showminnoactive+               7)
(defconstant +sw-showna+                        8)
(defconstant +sw-restore+                       9)
(defconstant +sw-showdefault+                  10)
(defconstant +sw-forceminimize+                11)
(defconstant +sw-max+                          11)

(defconstant +tb-lineup+                        0)
(defconstant +tb-linedown+                      1)
(defconstant +tb-pageup+                        2)
(defconstant +tb-pagedown+                      3)
(defconstant +tb-thumbposition+                 4)
(defconstant +tb-thumbtrack+                    5)
(defconstant +tb-top+                           6)
(defconstant +tb-bottom+                        7)
(defconstant +tb-endtrack+                      8)

(defconstant +swp-nosize+                  #x0001)
(defconstant +swp-nomove+                  #x0002)
(defconstant +swp-nozorder+                #x0004)
(defconstant +swp-noredraw+                #x0008)
(defconstant +swp-noactivate+              #x0010)
(defconstant +swp-framechanged+            #x0020)
(defconstant +swp-showwindow+              #x0040)
(defconstant +swp-hidewindow+              #x0080)
(defconstant +swp-nocopybits+              #x0100)
(defconstant +swp-noownerzorder+           #x0200)
(defconstant +swp-nosendchanging+          #x0400)
(defconstant +swp-drawframe+               #x0020)
(defconstant +swp-noreposition+            #x0200)
(defconstant +swp-defererase+              #x2000)
(defconstant +swp-asyncwindowpos+          #x4000)

(defconstant +tbm-getpos+               +wm-user+)
(defconstant +tbm-getrangemin+    (+ +wm-user+  1))
(defconstant +tbm-getrangemax+    (+ +wm-user+  2))
(defconstant +tbm-gettic+         (+ +wm-user+  3))
(defconstant +tbm-settic+         (+ +wm-user+  4))
(defconstant +tbm-setpos+         (+ +wm-user+  5))
(defconstant +tbm-setrange+       (+ +wm-user+  6))
(defconstant +tbm-setrangemin+    (+ +wm-user+  7))
(defconstant +tbm-setrangemax+    (+ +wm-user+  8))
(defconstant +tbm-cleartics+      (+ +wm-user+  9))
(defconstant +tbm-setsel+         (+ +wm-user+ 10))
(defconstant +tbm-setselstart+    (+ +wm-user+ 11))
(defconstant +tbm-setselend+      (+ +wm-user+ 12))
(defconstant +tbm-getptics+       (+ +wm-user+ 14))
(defconstant +tbm-getticpos+      (+ +wm-user+ 15))
(defconstant +tbm-getnumtics+     (+ +wm-user+ 16))
(defconstant +tbm-getselstart+    (+ +wm-user+ 17))
(defconstant +tbm-getselend+      (+ +wm-user+ 18))
(defconstant +tbm-clearsel+       (+ +wm-user+ 19))
(defconstant +tbm-setticfreq+     (+ +wm-user+ 20))
(defconstant +tbm-setpagesize+    (+ +wm-user+ 21))
(defconstant +tbm-getpagesize+    (+ +wm-user+ 22))
(defconstant +tbm-setlinesize+    (+ +wm-user+ 23))
(defconstant +tbm-getlinesize+    (+ +wm-user+ 24))
(defconstant +tbm-getthumbrect+   (+ +wm-user+ 25))
(defconstant +tbm-getchannelrect+ (+ +wm-user+ 26))
(defconstant +tbm-setthumblength+ (+ +wm-user+ 27))
(defconstant +tbm-getthumblength+ (+ +wm-user+ 28))

(defconstant +tbs-autoticks+               #x0001)
(defconstant +tbs-vert+                    #x0002)
(defconstant +tbs-horz+                    #x0000)
(defconstant +tbs-top+                     #x0004)
(defconstant +tbs-bottom+                  #x0000)
(defconstant +tbs-left+                    #x0004)
(defconstant +tbs-right+                   #x0000)
(defconstant +tbs-both+                    #x0008)
(defconstant +tbs-noticks+                 #x0010)
(defconstant +tbs-enableselrange+          #x0020)
(defconstant +tbs-fixedlength+             #x0040)
(defconstant +tbs-nothumb+                 #x0080)
(defconstant +tbs-tooltips+                #x0100)

(defconstant +tpm-leftbutton+              #x0000)
(defconstant +tpm-rightbutton+             #x0002)
(defconstant +tpm-leftalign+               #x0000)
(defconstant +tpm-centeralign+             #x0004)
(defconstant +tpm-rightalign+              #x0008)
(defconstant +tpm-topalign+                #x0000)
(defconstant +tpm-vcenteralign+            #x0010)
(defconstant +tpm-bottomalign+             #x0020)
(defconstant +tpm-horizontal+              #x0000)
(defconstant +tpm-vertical+                #x0040)
(defconstant +tpm-nonotify+                #x0080)
(defconstant +tpm-returncmd+               #x0100)
(defconstant +tpm-recurse+                 #x0001)
(defconstant +tpm-horposanimation+         #x0400)
(defconstant +tpm-horneganimation+         #x0800)
(defconstant +tpm-verposanimation+         #x1000)
(defconstant +tpm-verneganimation+         #x2000)
(defconstant +tpm-noanimation+             #x4000)
(defconstant +tpm-layoutrtl+               #x8000)

(defconstant +user-timer-maximum+      #x7FFFFFFF)
(defconstant +user-timer-minimum+      #x0000000A)

(defconstant +wa-inactive+                      0)
(defconstant +wa-active+                        1)
(defconstant +wa-clickactive+                   2)

(defconstant +wb-left+                          0)
(defconstant +wb-right+                         1)
(defconstant +wb-isdelimiter+                   2)

(defconstant +wm-create+                   #x0001)
(defconstant +wm-destroy+                  #x0002)
(defconstant +wm-move+                     #x0003)
(defconstant +wm-size+                     #x0005)
(defconstant +wm-activate+                 #x0006)
(defconstant +wm-setfocus+                 #x0007)
(defconstant +wm-killfocus+                #x0008)
(defconstant +wm-enable+                   #x000A)
(defconstant +wm-setredraw+                #x000B)
(defconstant +wm-settext+                  #x000C)
(defconstant +wm-gettext+                  #x000D)
(defconstant +wm-gettextlength+            #x000E)
(defconstant +wm-paint+                    #x000F)
(defconstant +wm-close+                    #x0010)
(defconstant +wm-queryendsession+          #x0011)
(defconstant +wm-queryopen+                #x0013)
(defconstant +wm-endsession+               #x0016)
(defconstant +wm-quit+                     #x0012)
(defconstant +wm-erasebkgnd+               #x0014)
(defconstant +wm-syscolorchange+           #x0015)
(defconstant +wm-showwindow+               #x0018)
(defconstant +wm-wininichange+             #x001A)
(defconstant +wm-settingchange+            #x001A)
(defconstant +wm-devmodechange+            #x001B)
(defconstant +wm-activateapp+              #x001C)
(defconstant +wm-fontchange+               #x001D)
(defconstant +wm-timechange+               #x001E)
(defconstant +wm-cancelmode+               #x001F)
(defconstant +wm-setcursor+                #x0020)
(defconstant +wm-mouseactivate+            #x0021)
(defconstant +wm-childactivate+            #x0022)
(defconstant +wm-queuesync+                #x0023)
(defconstant +wm-getminmaxinfo+            #x0024)
(defconstant +wm-painticon+                #x0026)
(defconstant +wm-iconerasebkgnd+           #x0027)
(defconstant +wm-nextdlgctl+               #x0028)
(defconstant +wm-spoolerstatus+            #x002A)
(defconstant +wm-drawitem+                 #x002B)
(defconstant +wm-measureitem+              #x002C)
(defconstant +wm-deleteitem+               #x002D)
(defconstant +wm-vkeytoitem+               #x002E)
(defconstant +wm-chartoitem+               #x002F)
(defconstant +wm-setfont+                  #x0030)
(defconstant +wm-getfont+                  #x0031)
(defconstant +wm-windowposchanging+        #x0046)
(defconstant +wm-windowposchanged+         #x0047)
(defconstant +wm-contextmenu+              #x007B)
(defconstant +wm-stylechanging+            #x007C)
(defconstant +wm-stylechanged+             #x007D)
(defconstant +wm-displaychange+            #x007E)
(defconstant +wm-geticon+                  #x007F)
(defconstant +wm-seticon+                  #x0080)
(defconstant +wm-nccreate+                 #x0081)
(defconstant +wm-ncdestroy+                #x0082)
(defconstant +wm-nccalcsize+               #x0083)
(defconstant +wm-nchittest+                #x0084)
(defconstant +wm-ncpaint+                  #x0085)
(defconstant +wm-ncactivate+               #x0086)
(defconstant +wm-getdlgcode+               #x0087)
(defconstant +wm-syncpaint+                #x0088)
(defconstant +wm-ncmousemove+              #x00A0)
(defconstant +wm-nclbuttondown+            #x00A1)
(defconstant +wm-nclbuttonup+              #x00A2)
(defconstant +wm-nclbuttondblclk+          #x00A3)
(defconstant +wm-ncrbuttondown+            #x00A4)
(defconstant +wm-ncrbuttonup+              #x00A5)
(defconstant +wm-ncrbuttondblclk+          #x00A6)
(defconstant +wm-ncmbuttondown+            #x00A7)
(defconstant +wm-ncmbuttonup+              #x00A8)
(defconstant +wm-ncmbuttondblclk+          #x00A9)
(defconstant +wm-ncxbuttondown+            #x00AB)
(defconstant +wm-ncxbuttonup+              #x00AC)
(defconstant +wm-ncxbuttondblclk+          #x00AD)
(defconstant +wm-keyfirst+                 #x0100) ; for use with peek-message
(defconstant +wm-keydown+                  #x0100)
(defconstant +wm-keyup+                    #x0101)
(defconstant +wm-char+                     #x0102)
(defconstant +wm-deadchar+                 #x0103)
(defconstant +wm-syskeydown+               #x0104)
(defconstant +wm-syskeyup+                 #x0105)
(defconstant +wm-syschar+                  #x0106)
(defconstant +wm-sysdeadchar+              #x0107)
(defconstant +wm-keylast+                  #x0109) ; for use with peek-message
(defconstant +wm-initdialog+               #x0110)
(defconstant +wm-command+                  #x0111)
(defconstant +wm-syscommand+               #x0112)
(defconstant +wm-timer+                    #x0113)
(defconstant +wm-hscroll+                  #x0114)
(defconstant +wm-vscroll+                  #x0115)
(defconstant +wm-initmenu+                 #x0116)
(defconstant +wm-initmenupopup+            #x0117)
(defconstant +wm-menuselect+               #x011F)
(defconstant +wm-menuchar+                 #x0120)
(defconstant +wm-ctlcolormsgbox+           #x0132)
(defconstant +wm-ctlcoloredit+             #x0133)
(defconstant +wm-ctlcolorlistbox+          #x0134)
(defconstant +wm-ctlcolorbtn+              #x0135)
(defconstant +wm-ctlcolordlg+              #x0136)
(defconstant +wm-ctlcolorscrollbar+        #x0137)
(defconstant +wm-ctlcolorstatic+           #x0138)
(defconstant +wm-mousefirst+               #x0200) ; for use with peek-message
(defconstant +wm-mousemove+                #x0200)
(defconstant +wm-lbuttondown+              #x0201)
(defconstant +wm-lbuttonup+                #x0202)
(defconstant +wm-lbuttondblclk+            #x0203)
(defconstant +wm-rbuttondown+              #x0204)
(defconstant +wm-rbuttonup+                #x0205)
(defconstant +wm-rbuttondblclk+            #x0206)
(defconstant +wm-mbuttondown+              #x0207)
(defconstant +wm-mbuttonup+                #x0208)
(defconstant +wm-mbuttondblclk+            #x0209)
(defconstant +wm-mousewheel+               #x020A)
(defconstant +wm-xbuttondown+              #x020B)
(defconstant +wm-xbuttonup+                #x020C)
(defconstant +wm-xbuttondblclk+            #x020D)
(defconstant +wm-mouselast+                #x020D) ; for use with peek-message
(defconstant +wm-sizing+                   #x0214)
(defconstant +wm-moving+                   #x0216)
(defconstant +wm-ncmousehover+             #x02A0)
(defconstant +wm-mousehover+               #x02A1)
(defconstant +wm-ncmouseleave+             #x02A2)
(defconstant +wm-mouseleave+               #x02A3)
(defconstant +wm-cut+                      #x0300)
(defconstant +wm-copy+                     #x0301)
(defconstant +wm-paste+                    #x0302)
(defconstant +wm-clear+                    #x0303)
(defconstant +wm-undo+                     #x0304)
(defconstant +wm-renderformat+             #x0305)
(defconstant +wm-renderallformats+         #x0306)
(defconstant +wm-destroyclipboard+         #x0307)
(defconstant +wm-drawclipboard+            #x0308)
(defconstant +wm-paintclipboard+           #x0309)
(defconstant +wm-vscrollclipboard+         #x030A)
(defconstant +wm-sizeclipboard+            #x030B)
(defconstant +wm-askcbformatname+          #x030C)
(defconstant +wm-changecbchain+            #x030D)
(defconstant +wm-hscrollclipboard+         #x030E)
(defconstant +wm-querynewpalette+          #x030F)
(defconstant +wm-paletteischanging+        #x0310)
(defconstant +wm-palettechanged+           #x0311)
(defconstant +wm-hotkey+                   #x0312)
(defconstant +wm-print+                    #x0317)
(defconstant +wm-printclient+              #x0318)
(defconstant +wm-appcommand+               #x0319)
(defconstant +wm-themechanged+             #x031A)

(defconstant +wmsz-left+                        1)
(defconstant +wmsz-right+                       2)
(defconstant +wmsz-top+                         3)
(defconstant +wmsz-topleft+                     4)
(defconstant +wmsz-topright+                    5)
(defconstant +wmsz-bottom+                      6)
(defconstant +wmsz-bottomleft+                  7)
(defconstant +wmsz-bottomright+                 8)

(defconstant +ws-overlapped+           #x00000000)
(defconstant +ws-popup+                #x80000000)
(defconstant +ws-child+                #x40000000)
(defconstant +ws-minimize+             #x20000000)
(defconstant +ws-visible+              #x10000000)
(defconstant +ws-disabled+             #x08000000)
(defconstant +ws-clipsiblings+         #x04000000)
(defconstant +ws-clipchildren+         #x02000000)
(defconstant +ws-maximize+             #x01000000)
(defconstant +ws-caption+              #x00C00000)
(defconstant +ws-border+               #x00800000)
(defconstant +ws-dlgframe+             #x00400000)
(defconstant +ws-vscroll+              #x00200000)
(defconstant +ws-hscroll+              #x00100000)
(defconstant +ws-sysmenu+              #x00080000)
(defconstant +ws-thickframe+           #x00040000)
(defconstant +ws-group+                #x00020000)
(defconstant +ws-minimizebox+          #x00020000)
(defconstant +ws-maximizebox+          #x00010000)
(defconstant +ws-tabstop+              #x00010000)
(defconstant +ws-popupwindow+          #x80880000)
(defconstant +ws-overlappedwindow+     #x00CF0000)

(defconstant +ws-ex-dlgmodalframe+     #x00000001)
(defconstant +ws-ex-noparentnotify+    #x00000004)
(defconstant +ws-ex-topmost+           #x00000008)
(defconstant +ws-ex-acceptfiles+       #x00000010)
(defconstant +ws-ex-transparent+       #x00000020)
(defconstant +ws-ex-mdichild+          #x00000040)
(defconstant +ws-ex-toolwindow+        #x00000080)
(defconstant +ws-ex-windowedge+        #x00000100)
(defconstant +ws-ex-clientedge+        #x00000200)
(defconstant +ws-ex-contexthelp+       #x00000400)
(defconstant +ws-ex-right+             #x00001000)
(defconstant +ws-ex-left+              #x00000000)
(defconstant +ws-ex-rtlreading+        #x00002000)
(defconstant +ws-ex-ltrreading+        #x00000000)
(defconstant +ws-ex-leftscrollbar+     #x00004000)
(defconstant +ws-ex-rightscrollbar+    #x00000000)
(defconstant +ws-ex-controlparent+     #x00010000)
(defconstant +ws-ex-staticedge+        #x00020000)
(defconstant +ws-ex-appwindow+         #x00040000)
(defconstant +ws-ex-overlappedwindow+  #x00000300)
(defconstant +ws-ex-palettewindow+     #x00000188)
(defconstant +ws-ex-layered+           #x00080000)
(defconstant +ws-ex-noinheritlayout+   #x00100000)
(defconstant +ws-ex-layoutrtl+         #x00400000)
(defconstant +ws-ex-composited+        #x02000000)
(defconstant +ws-ex-noactivate+        #x08000000)

(defconstant +wvr-aligntop+                #x0010)
(defconstant +wvr-alignleft+               #x0020)
(defconstant +wvr-alignbottom+             #x0040)
(defconstant +wvr-alignright+              #x0080)
(defconstant +wvr-hredraw+                 #x0100)
(defconstant +wvr-vredraw+                 #x0200)
(defconstant +wvr-redraw+                  #x0300)
(defconstant +wvr-validrects+              #x0400)

(defconstant +white-brush+                      0)
(defconstant +ltgray-brush+                     1)
(defconstant +gray-brush+                       2)
(defconstant +dkgray-brush+                     3)
(defconstant +black-brush+                      4)
(defconstant +null-brush+                       5)
(defconstant +hollow-brush+                     5)
(defconstant +white-pen+                        6)
(defconstant +black-pen+                        7)
(defconstant +null-pen+                         8)
(defconstant +oem-fixed-font+                  10)
(defconstant +ansi-fixed-font+                 11)
(defconstant +ansi-var-font+                   12)
(defconstant +system-font+                     13)
(defconstant +device-default-font+             14)
(defconstant +default-palette+                 15)
(defconstant +system-fixed-font+               16)
(defconstant +default-gui-font+                17)
(defconstant +dc-brush+                        18)
(defconstant +dc-pen+                          19)

(defconstant +default-pitch+                    0)
(defconstant +fixed-pitch+                      1)
(defconstant +variable-pitch+                   2)

;;;
;;; device parameters for get-device-caps
;;;
(defconstant +driverversion+                    0)
(defconstant +technology+                       2)
(defconstant +horzsize+                         4)
(defconstant +vertsize+                         6)
(defconstant +horzres+                          8)
(defconstant +vertres+                         10)
(defconstant +bitspixel+                       12)
(defconstant +planes+                          14)
(defconstant +numbrushes+                      16)
(defconstant +numpens+                         18)
(defconstant +nummarkers+                      20)
(defconstant +numfonts+                        22)
(defconstant +numcolors+                       24)
(defconstant +pdevicesize+                     26)
(defconstant +curvecaps+                       28)
(defconstant +linecaps+                        30)
(defconstant +polygonalcaps+                   32)
(defconstant +textcaps+                        34)
(defconstant +clipcaps+                        36)
(defconstant +rastercaps+                      38)
(defconstant +aspectx+                         40)
(defconstant +aspecty+                         42)
(defconstant +aspectxy+                        44)
(defconstant +logpixelsx+                      88)
(defconstant +logpixelsy+                      90)
(defconstant +sizepalette+                    104)
(defconstant +numreserved+                    106)
(defconstant +colorres+                       108)
(defconstant +physicalwidth+                  110)
(defconstant +physicalheight+                 111)
(defconstant +physicaloffsetx+                112)
(defconstant +physicaloffsety+                113)
(defconstant +scalingfactorx+                 114)
(defconstant +scalingfactory+                 115)
(defconstant +vrefresh+                       116)
(defconstant +desktopvertres+                 117)
(defconstant +desktophorzres+                 118)
(defconstant +bltalignment+                   119)
(defconstant +shadeblendcaps+                 120)
(defconstant +colormgmtcaps+                  121)

;;;
;;; LoadLibraryEx flags
;;;
(defconstant +dont-resolve-dll-references+   #x00000001)
(defconstant +load-library-as-datafile+      #x00000002)
(defconstant +load-with-altered-search-path+ #x00000008)
(defconstant +load-ignore-code-authz-level+  #x00000010)

;;;
;;; Background modes (Get/SetBkMode)
;;;
(defconstant +transparent+                      1)
(defconstant +opaque+                           2)
