DIRS = rel1 rel2 rel3 rel4 rel5 rel6
# Note: rel1, rel2, and rel3 still exist, but are no longer distributed.
# File ../Makefile-psubdirs is engineered to skip gracefully over any missing
# subdirectories.
include ../Makefile-psubdirs
