#!/bin/sh
top_srcdir=`(cd \`dirname $0\` > /dev/null 2>&1 ; pwd)`
MAXIMA_PREFIX=$top_srcdir
export MAXIMA_PREFIX
MAXIMA_LAYOUT_AUTOTOOLS=false
export MAXIMA_LAYOUT_AUTOTOOLS

POSIX_SHELL=/bin/sh
exec $POSIX_SHELL $top_srcdir/src/maxima "$@"
